using System.Collections.Immutable;
using System.Globalization;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

using Shared;

namespace HostingWebhookEventsGenerator;

[Generator(LanguageNames.CSharp)]
public class HostingWebhookEventsGenerator : IIncrementalGenerator
{
    private const string Namespace = "NetCord.Hosting.AspNetCore";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(context =>
        {
            context.AddSource("GenerateHandlerAttribute.g.cs", SourceText.From(
                """
                #nullable enable

                namespace NetCord.Hosting.AspNetCore;

                [AttributeUsage(AttributeTargets.Class, AllowMultiple = true)]
                internal class GenerateHandlerAttribute(string? rawEventName, Type? eventArgs) : Attribute
                {
                    public string? RawEventName => rawEventName;

                    public Type? EventArgs => eventArgs;
                }

                """, Encoding.UTF8));
        });

        var attributesData = context.SyntaxProvider.ForAttributeWithMetadataName("NetCord.Hosting.AspNetCore.GenerateHandlerAttribute",
                                                            (syntaxNode, cancellationToken) => syntaxNode is ClassDeclarationSyntax,
                                                            (context, cancellationToken) =>
                                                            {
                                                                return context.Attributes
                                                                    .Where(a => a.ConstructorArguments.Length >= 2)
                                                                    .Select(a =>
                                                                    {
                                                                        var constructorArguments = a.ConstructorArguments;
                                                                        return new GenerateHandlerAttributeData((string?)constructorArguments[0].Value, (INamedTypeSymbol)constructorArguments[1].Value!);
                                                                    });
                                                            })
            .SelectMany((data, cancellationToken) => data)
            .Collect();

        context.RegisterSourceOutput(attributesData, (context, attributesData) =>
        {
            context.AddSource("WebhookEvent.g.cs", SourceText.From(GenerateEvents(attributesData), Encoding.UTF8));

            context.AddSource("WebhookHandlerInterfaces.g.cs", SourceText.From(GenerateHandlerInterfaces(attributesData), Encoding.UTF8));

            context.AddSource("WebhookEventHandlerInvoker.g.cs", SourceText.From(GenerateWebhookEventHandlerInvoker(attributesData), Encoding.UTF8));
        });
    }

    private class GenerateHandlerAttributeData(string? rawEventName, INamedTypeSymbol? eventArgs)
    {
        public string? RawEventName => rawEventName;

        public string EventName { get; } = GetEventName(rawEventName);

        public INamedTypeSymbol? EventArgs => eventArgs;

        private static string GetEventName(string? rawEventName)
        {
            if (rawEventName is null)
                return "UnknownEvent";

            var textInfo = CultureInfo.InvariantCulture.TextInfo;

            var result = textInfo.ToLower(rawEventName);

            result = textInfo.ToTitleCase(result);

            result = result.Replace("_", string.Empty);

            return result;
        }
    }

    private static void Setup(StringWriter stringWriter)
    {
        stringWriter.WriteAutoGeneratedComment();
        stringWriter.WriteLine();

        stringWriter.WriteNullableDirective();
        stringWriter.WriteLine();

        stringWriter.Write("namespace ");
        stringWriter.Write(Namespace);
        stringWriter.WriteLine(";");
    }

    private string GenerateEvents(ImmutableArray<GenerateHandlerAttributeData> attributesData)
    {
        StringWriter stringWriter = new();
        Setup(stringWriter);

        WriteEventsEnum(stringWriter, attributesData);

        WriteEvents(stringWriter, attributesData);

        return stringWriter.ToString();
    }

    private void WriteEvents(StringWriter stringWriter, ImmutableArray<GenerateHandlerAttributeData> attributesData)
    {
        stringWriter.WriteLine();

        stringWriter.WriteLine("partial class WebhookEvent");
        stringWriter.Write("{");

        foreach (var attributeData in attributesData)
        {
            var eventArgs = attributeData.EventArgs;

            stringWriter.WriteLine();

            if (eventArgs is not null)
                stringWriter.WriteInheritDoc(eventArgs, 1);

            stringWriter.WriteIndentation(1);
            stringWriter.Write("public static global::");
            stringWriter.Write(Namespace);
            stringWriter.Write(".WebhookEvent");

            if (eventArgs is not null)
            {
                stringWriter.Write("<");
                stringWriter.Write(eventArgs.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
                stringWriter.Write("> ");
            }

            var eventName = attributeData.EventName;

            stringWriter.Write(eventName);
            stringWriter.Write(" => new(global::NetCord.Hosting.AspNetCore.WebhookEventId.");

            stringWriter.Write(eventName);

            stringWriter.WriteLine(");");
        }

        stringWriter.WriteLine("}");
    }

    private void WriteEventsEnum(StringWriter stringWriter, ImmutableArray<GenerateHandlerAttributeData> attributesData)
    {
        stringWriter.WriteLine();

        stringWriter.WriteLine("internal enum WebhookEventId : byte");

        stringWriter.WriteLine("{");

        int attributeCount = attributesData.Length;
        for (int i = 0; i < attributeCount; i++)
        {
            var attributeData = attributesData[i];

            stringWriter.WriteIndentation(1);
            stringWriter.Write(attributeData.EventName);
            stringWriter.WriteLine(",");
        }

        stringWriter.WriteLine("}");
    }

    private string GenerateHandlerInterfaces(ImmutableArray<GenerateHandlerAttributeData> attributesData)
    {
        StringWriter stringWriter = new();
        Setup(stringWriter);

        WriteHandlerInterfaces(stringWriter, attributesData);

        return stringWriter.ToString();
    }

    private void WriteHandlerInterfaces(StringWriter stringWriter, ImmutableArray<GenerateHandlerAttributeData> attributesData)
    {
        foreach (var attributeData in attributesData)
        {
            var eventArgs = attributeData.EventArgs;

            stringWriter.WriteLine();

            if (eventArgs is not null)
                stringWriter.WriteInheritDoc(eventArgs, 0);

            stringWriter.Write("public interface I");
            stringWriter.Write(attributeData.EventName);
            stringWriter.WriteLine("WebhookHandler : global::NetCord.Hosting.AspNetCore.IWebhookHandler");

            stringWriter.WriteLine("{");

            stringWriter.WriteIndentation(1);
            stringWriter.Write("public global::System.Threading.Tasks.ValueTask HandleAsync(");

            if (eventArgs is not null)
            {
                stringWriter.Write(eventArgs.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
                stringWriter.Write(" arg");
            }

            stringWriter.WriteLine(");");

            stringWriter.WriteLine("}");
        }
    }

    private string GenerateWebhookEventHandlerInvoker(ImmutableArray<GenerateHandlerAttributeData> attributesData)
    {
        StringWriter stringWriter = new();
        Setup(stringWriter);

        WriteWebhookEventHandlerInvoker(stringWriter, attributesData);

        return stringWriter.ToString();
    }

    private void WriteWebhookEventHandlerInvoker(StringWriter stringWriter, ImmutableArray<GenerateHandlerAttributeData> attributesData)
    {
        stringWriter.WriteLine();

        stringWriter.WriteLine("partial class WebhookEventHandlerInvoker");

        stringWriter.Write("{");

        WriteStorageBuilder(stringWriter, attributesData);

        WriteStorage(stringWriter, attributesData);

        WriteHandleEventAsyncMethod(stringWriter, attributesData);

        stringWriter.WriteLine("}");
    }

    private void WriteStorageBuilder(StringWriter stringWriter, ImmutableArray<GenerateHandlerAttributeData> attributesData)
    {
        stringWriter.WriteLine();

        stringWriter.WriteIndentation(1);
        stringWriter.WriteLine("partial class StorageBuilder");

        stringWriter.WriteIndentation(1);
        stringWriter.Write("{");

        WriteStorageBuilderFields(stringWriter, attributesData);

        WriteRegisterDelegateHandlerMethod(stringWriter, attributesData);

        WriteRegisterClassHandlerMethod(stringWriter, attributesData);

        WriteStorageBuilderBuildMethod(stringWriter, attributesData);

        stringWriter.WriteIndentation(1);
        stringWriter.WriteLine("}");
    }

    private void WriteStorageBuilderFields(StringWriter stringWriter, ImmutableArray<GenerateHandlerAttributeData> attributesData)
    {
        foreach (var attributeData in attributesData)
        {
            stringWriter.WriteLine();

            stringWriter.WriteIndentation(2);
            stringWriter.Write("private global::System.Collections.Generic.List<global::System.Func<");

            if (attributeData.EventArgs is { } eventArgs)
            {
                stringWriter.Write(eventArgs.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
                stringWriter.Write(", ");
            }

            stringWriter.Write("global::System.Threading.Tasks.ValueTask>> ");

            stringWriter.Write(ToInternalName(attributeData.EventName));
            stringWriter.WriteLine(" = [];");
        }
    }

    private void WriteRegisterDelegateHandlerMethod(StringWriter stringWriter, ImmutableArray<GenerateHandlerAttributeData> attributesData)
    {
        stringWriter.WriteLine();

        stringWriter.WriteIndentation(2);
        stringWriter.WriteLine("public void RegisterDelegateHandler(global::NetCord.Hosting.AspNetCore.DelegateWebhookHandlerMetadata handlerMetadata, IServiceProvider services)");

        stringWriter.WriteIndentation(2);
        stringWriter.WriteLine("{");

        stringWriter.WriteIndentation(3);
        stringWriter.WriteLine("var isSingleton = handlerMetadata.IsSingleton;");

        stringWriter.WriteIndentation(3);
        stringWriter.WriteLine("switch (handlerMetadata.EventId)");

        stringWriter.WriteIndentation(3);
        stringWriter.WriteLine("{");

        int attributeCount = attributesData.Length;

        for (var i = 0; i < attributeCount; i++)
        {
            var attributeData = attributesData[i];

            stringWriter.WriteIndentation(4);
            stringWriter.Write("case global::NetCord.Hosting.AspNetCore.WebhookEventId.");
            stringWriter.Write(attributeData.EventName);
            stringWriter.WriteLine(":");

            stringWriter.WriteIndentation(5);
            stringWriter.Write("var typedHandler");
            stringWriter.Write(i);
            stringWriter.Write(" = (global::System.Func<");

            var eventArgs = attributeData.EventArgs;
            if (eventArgs is not null)
            {
                stringWriter.Write(eventArgs.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
                stringWriter.Write(", ");
            }

            stringWriter.WriteLine("global::System.IServiceProvider, global::System.Threading.Tasks.ValueTask>)handlerMetadata.Handler;");

            stringWriter.WriteIndentation(5);
            stringWriter.Write(ToInternalName(attributeData.EventName));
            stringWriter.WriteLine(".Add(isSingleton");

            stringWriter.WriteIndentation(6);
            stringWriter.Write("? (");

            if (eventArgs is not null)
                stringWriter.Write("arg");

            stringWriter.Write(") => typedHandler");
            stringWriter.Write(i);
            stringWriter.Write("(");

            if (eventArgs is not null)
                stringWriter.Write("arg, ");

            stringWriter.WriteLine("services)");

            stringWriter.WriteIndentation(6);
            stringWriter.Write(": async (");

            if (eventArgs is not null)
                stringWriter.Write("arg");

            stringWriter.WriteLine(") =>");

            stringWriter.WriteIndentation(6);
            stringWriter.WriteLine("{");

            stringWriter.WriteIndentation(7);
            stringWriter.WriteLine("await using var scope = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.CreateAsyncScope(services);");

            stringWriter.WriteIndentation(7);
            stringWriter.Write("await typedHandler");
            stringWriter.Write(i);
            stringWriter.Write("(");

            if (eventArgs is not null)
                stringWriter.Write("arg, ");

            stringWriter.WriteLine("scope.ServiceProvider);");

            stringWriter.WriteIndentation(6);
            stringWriter.WriteLine("});");

            stringWriter.WriteIndentation(5);
            stringWriter.WriteLine("break;");
        }

        stringWriter.WriteIndentation(3);
        stringWriter.WriteLine("}");

        stringWriter.WriteIndentation(2);
        stringWriter.WriteLine("}");
    }

    private void WriteRegisterClassHandlerMethod(StringWriter stringWriter, ImmutableArray<GenerateHandlerAttributeData> attributesData)
    {
        stringWriter.WriteLine();

        stringWriter.WriteIndentation(2);
        stringWriter.WriteLine("public void RegisterClassHandler(global::NetCord.Hosting.AspNetCore.ClassWebhookHandlerMetadata handlerMetadata, IServiceProvider services)");

        stringWriter.WriteIndentation(2);
        stringWriter.WriteLine("{");

        stringWriter.WriteIndentation(3);
        stringWriter.WriteLine("var handlerType = handlerMetadata.HandlerType;");

        stringWriter.WriteIndentation(3);
        stringWriter.WriteLine("var isSingleton = handlerMetadata.IsSingleton;");

        stringWriter.WriteIndentation(3);
        stringWriter.WriteLine("var instanceFactory = handlerMetadata.InstanceFactory;");

        int attributeCount = attributesData.Length;

        for (int i = 0; i < attributeCount; i++)
        {
            var attributeData = attributesData[i];

            stringWriter.WriteLine();

            stringWriter.WriteIndentation(3);
            stringWriter.Write("if (typeof(global::NetCord.Hosting.AspNetCore.I");
            stringWriter.Write(attributeData.EventName);
            stringWriter.WriteLine("WebhookHandler).IsAssignableFrom(handlerType))");

            stringWriter.WriteIndentation(3);
            stringWriter.WriteLine("{");

            stringWriter.WriteIndentation(4);
            stringWriter.Write(ToInternalName(attributeData.EventName));
            stringWriter.WriteLine(".Add(isSingleton");

            stringWriter.WriteIndentation(5);
            stringWriter.Write("? ");

            stringWriter.Write("((global::NetCord.Hosting.AspNetCore.I");
            stringWriter.Write(attributeData.EventName);
            stringWriter.WriteLine("WebhookHandler)instanceFactory(services)).HandleAsync");

            stringWriter.WriteIndentation(5);
            stringWriter.Write(": async (");

            if (attributeData.EventArgs is not null)
                stringWriter.Write("arg");

            stringWriter.WriteLine(") =>");

            stringWriter.WriteIndentation(5);
            stringWriter.WriteLine("{");

            stringWriter.WriteIndentation(6);
            stringWriter.WriteLine("await using var scope = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.CreateAsyncScope(services);");

            stringWriter.WriteIndentation(6);

            stringWriter.Write("await ((global::NetCord.Hosting.AspNetCore.I");
            stringWriter.Write(attributeData.EventName);
            stringWriter.Write("WebhookHandler)instanceFactory(scope.ServiceProvider)).HandleAsync(");

            if (attributeData.EventArgs is not null)
                stringWriter.Write("arg");

            stringWriter.WriteLine(");");
            stringWriter.WriteIndentation(5);
            stringWriter.WriteLine("});");

            stringWriter.WriteIndentation(4);
            stringWriter.WriteLine("}");
        }

        stringWriter.WriteIndentation(2);
        stringWriter.WriteLine("}");
    }

    private void WriteStorageBuilderBuildMethod(StringWriter stringWriter, ImmutableArray<GenerateHandlerAttributeData> attributesData)
    {
        stringWriter.WriteLine();

        stringWriter.WriteIndentation(2);
        stringWriter.WriteLine("public global::NetCord.Hosting.AspNetCore.WebhookEventHandlerInvoker.Storage Build()");

        stringWriter.WriteIndentation(2);
        stringWriter.WriteLine("{");

        stringWriter.WriteIndentation(3);
        stringWriter.WriteLine("return new()");

        stringWriter.WriteIndentation(3);
        stringWriter.WriteLine("{");

        int attributeCount = attributesData.Length;
        for (int i = 0; i < attributeCount; i++)
        {
            var attributeData = attributesData[i];

            var internalName = ToInternalName(attributeData.EventName);

            stringWriter.WriteIndentation(4);
            stringWriter.Write(internalName);
            stringWriter.Write(" = [.. ");
            stringWriter.Write(internalName);
            stringWriter.WriteLine("],");
        }

        stringWriter.WriteIndentation(3);
        stringWriter.WriteLine("};");

        stringWriter.WriteIndentation(2);
        stringWriter.WriteLine("}");
    }

    private void WriteStorage(StringWriter stringWriter, ImmutableArray<GenerateHandlerAttributeData> attributesData)
    {
        stringWriter.WriteLine();

        stringWriter.WriteIndentation(1);
        stringWriter.WriteLine("partial class Storage");

        stringWriter.WriteIndentation(1);
        stringWriter.Write("{");

        WriteStorageFields(stringWriter, attributesData);

        stringWriter.WriteIndentation(1);
        stringWriter.WriteLine("}");
    }

    private void WriteStorageFields(StringWriter stringWriter, ImmutableArray<GenerateHandlerAttributeData> attributesData)
    {
        foreach (var attributeData in attributesData)
        {
            stringWriter.WriteLine();

            stringWriter.WriteIndentation(2);
            stringWriter.Write("internal required global::System.Func<");

            if (attributeData.EventArgs is { } eventArgs)
            {
                stringWriter.Write(eventArgs.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
                stringWriter.Write(", ");
            }

            stringWriter.Write("global::System.Threading.Tasks.ValueTask>[] ");
            stringWriter.Write(ToInternalName(attributeData.EventName));
            stringWriter.WriteLine(";");
        }
    }

    private void WriteHandleEventAsyncMethod(StringWriter stringWriter, ImmutableArray<GenerateHandlerAttributeData> attributesData)
    {
        stringWriter.WriteLine();

        stringWriter.WriteIndentation(1);
        stringWriter.WriteLine("private global::System.Threading.Tasks.ValueTask HandleEventAsync(global::NetCord.Rest.WebhookEventArgs data)");

        stringWriter.WriteIndentation(1);
        stringWriter.WriteLine("{");

        stringWriter.WriteIndentation(2);
        stringWriter.WriteLine("return data.Type switch");

        stringWriter.WriteIndentation(2);
        stringWriter.Write("{");

        foreach (var attributeData in attributesData)
        {
            stringWriter.WriteLine();

            stringWriter.WriteIndentation(3);
            if (attributeData.RawEventName is null)
                stringWriter.Write("_ => ");
            else
            {
                stringWriter.Write("\"");
                stringWriter.Write(attributeData.RawEventName);
                stringWriter.Write("\" => ");
            }

            stringWriter.Write("InvokeHandlersAsync(_storage.");
            stringWriter.Write(ToInternalName(attributeData.EventName));
            if (attributeData.EventArgs is { } eventArgs)
            {
                stringWriter.Write(", (");
                stringWriter.Write(eventArgs.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
                stringWriter.Write(")data),");
            }
            else
                stringWriter.Write("),");
        }

        stringWriter.WriteLine();

        stringWriter.WriteIndentation(2);
        stringWriter.WriteLine("};");

        stringWriter.WriteIndentation(1);
        stringWriter.WriteLine("}");
    }

    private static Span<char> ToInternalName(string name)
    {
        Span<char> copy = new char[name.Length + 1];
        copy[0] = '_';
        name.AsSpan(1).CopyTo(copy[2..]);
        copy[1] = char.ToLowerInvariant(name[0]);
        return copy;
    }
}
