using System.Collections.Immutable;
using System.Globalization;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

using Shared;

namespace HostingWebhookEventsGenerator;

[Generator(LanguageNames.CSharp)]
public class HostingWebhookEventsGenerator : IIncrementalGenerator
{
    private const string Namespace = "NetCord.Hosting.AspNetCore";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(context =>
        {
            context.AddSource("GenerateHandlerAttribute.g.cs", SourceText.From(
                """
                #nullable enable

                namespace NetCord.Hosting.AspNetCore;

                [AttributeUsage(AttributeTargets.Class, AllowMultiple = true)]
                internal class GenerateHandlerAttribute(string? rawEventName, Type eventArgs) : Attribute
                {
                    public string? RawEventName => rawEventName;

                    public Type EventArgs => eventArgs;
                }

                """, Encoding.UTF8));
        });

        var attributesData = context.SyntaxProvider.ForAttributeWithMetadataName("NetCord.Hosting.AspNetCore.GenerateHandlerAttribute",
                                                            (syntaxNode, cancellationToken) => syntaxNode is ClassDeclarationSyntax,
                                                            (context, cancellationToken) =>
                                                            {
                                                                return context.Attributes
                                                                    .Where(a => a.ConstructorArguments.Length >= 2)
                                                                    .Select(a =>
                                                                    {
                                                                        var constructorArguments = a.ConstructorArguments;
                                                                        return new GenerateHandlerAttributeData((string?)constructorArguments[0].Value, (INamedTypeSymbol)constructorArguments[1].Value!);
                                                                    });
                                                            })
            .SelectMany((data, cancellationToken) => data)
            .Collect();

        context.RegisterSourceOutput(attributesData, (context, attributesData) =>
        {
            context.AddSource("WebhookEvent.g.cs", SourceText.From(GenerateEvents(attributesData), Encoding.UTF8));

            context.AddSource("WebhookEventHandlerInterfaces.g.cs", SourceText.From(GenerateHandlerInterfaces(attributesData), Encoding.UTF8));

            context.AddSource("WebhookEventHandler.g.cs", SourceText.From(GenerateWebhookEventHandler(attributesData), Encoding.UTF8));
        });
    }

    private readonly record struct GenerateHandlerAttributeData(string? RawEventName, INamedTypeSymbol EventArgs)
    {
        public string EventName
        {
            get
            {
                if (RawEventName is null)
                    return "UnknownEvent";

                var textInfo = CultureInfo.InvariantCulture.TextInfo;

                var result = textInfo.ToLower(RawEventName);

                result = textInfo.ToTitleCase(result);

                result = result.Replace("_", string.Empty);

                return result;
            }
        }
    }

    private static void Setup(StringWriter stringWriter)
    {
        stringWriter.WriteAutoGeneratedComment();
        stringWriter.WriteLine();

        stringWriter.WriteNullableDirective();
        stringWriter.WriteLine();

        stringWriter.Write("namespace ");
        stringWriter.Write(Namespace);
        stringWriter.WriteLine(";");
    }

    private string GenerateEvents(ImmutableArray<GenerateHandlerAttributeData> attributesData)
    {
        StringWriter stringWriter = new();
        Setup(stringWriter);

        WriteEvents(stringWriter, attributesData);

        return stringWriter.ToString();
    }

    private void WriteEvents(StringWriter stringWriter, ImmutableArray<GenerateHandlerAttributeData> attributesData)
    {
        stringWriter.WriteLine();

        stringWriter.WriteLine("partial class WebhookEvent");
        stringWriter.Write("{");

        foreach (var attributeData in attributesData)
        {
            var eventArgs = attributeData.EventArgs;

            stringWriter.WriteLine();

            stringWriter.WriteXmlComment(eventArgs, 1);

            stringWriter.WriteIndentation(1);
            stringWriter.Write("public static global::");
            stringWriter.Write(Namespace);
            stringWriter.Write(".WebhookEvent");
            stringWriter.Write("<");
            stringWriter.Write(eventArgs.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
            stringWriter.Write("> ");

            stringWriter.Write(attributeData.EventName);
            stringWriter.Write(" => new(");

            if (attributeData.RawEventName is null)
                stringWriter.Write("null");
            else
            {
                stringWriter.Write("\"");
                stringWriter.Write(attributeData.RawEventName);
                stringWriter.Write("\"");
            }

            stringWriter.WriteLine(");");
        }

        stringWriter.WriteLine("}");
    }

    private string GenerateHandlerInterfaces(ImmutableArray<GenerateHandlerAttributeData> attributesData)
    {
        StringWriter stringWriter = new();
        Setup(stringWriter);

        WriteHandlerInterfaces(stringWriter, attributesData);

        return stringWriter.ToString();
    }

    private void WriteHandlerInterfaces(StringWriter stringWriter, ImmutableArray<GenerateHandlerAttributeData> attributesData)
    {
        foreach (var attributeData in attributesData)
        {
            var eventArgs = attributeData.EventArgs;
            
            stringWriter.WriteLine();

            stringWriter.WriteXmlComment(eventArgs, 0);

            stringWriter.Write("public interface I");
            stringWriter.Write(attributeData.EventName);
            stringWriter.WriteLine("WebhookEventHandler : global::NetCord.Hosting.AspNetCore.IWebhookEventHandler");

            stringWriter.WriteLine("{");

            stringWriter.WriteIndentation(1);
            stringWriter.Write("public global::System.Threading.Tasks.ValueTask HandleAsync(");

            stringWriter.Write(eventArgs.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
            stringWriter.Write(" arg");

            stringWriter.WriteLine(");");

            stringWriter.WriteLine("}");
        }
    }

    private string GenerateWebhookEventHandler(ImmutableArray<GenerateHandlerAttributeData> attributesData)
    {
        StringWriter stringWriter = new();
        Setup(stringWriter);

        WriteWebhookEventHandler(stringWriter, attributesData);

        return stringWriter.ToString();
    }

    private void WriteWebhookEventHandler(StringWriter stringWriter, ImmutableArray<GenerateHandlerAttributeData> attributesData)
    {
        stringWriter.WriteLine();

        stringWriter.WriteLine("partial class WebhookEventHandler");

        stringWriter.Write("{");

        WriteStorageBuilder(stringWriter, attributesData);

        WriteStorage(stringWriter, attributesData);

        WriteHandleEventAsyncMethod(stringWriter, attributesData);

        stringWriter.WriteLine("}");
    }

    private void WriteStorageBuilder(StringWriter stringWriter, ImmutableArray<GenerateHandlerAttributeData> attributesData)
    {
        stringWriter.WriteLine();

        stringWriter.WriteIndentation(1);
        stringWriter.WriteLine("partial class StorageBuilder");

        stringWriter.WriteIndentation(1);
        stringWriter.Write("{");

        WriteStorageBuilderFields(stringWriter, attributesData);

        WriteRegisterDelegateHandlerMethod(stringWriter, attributesData);

        WriteRegisterClassHandlerMethod(stringWriter, attributesData);

        WriteStorageBuilderBuildMethod(stringWriter, attributesData);

        stringWriter.WriteIndentation(1);
        stringWriter.WriteLine("}");
    }

    private void WriteStorageBuilderFields(StringWriter stringWriter, ImmutableArray<GenerateHandlerAttributeData> attributesData)
    {
        foreach (var attributeData in attributesData)
        {
            stringWriter.WriteLine();

            stringWriter.WriteIndentation(2);
            stringWriter.Write("private global::System.Collections.Generic.List<global::System.Func<");
            stringWriter.Write(attributeData.EventArgs.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
            stringWriter.Write(", global::System.Threading.Tasks.ValueTask>> ");
            stringWriter.Write(ToInternalName(attributeData.EventName));
            stringWriter.WriteLine(" = [];");
        }
    }

    private void WriteRegisterDelegateHandlerMethod(StringWriter stringWriter, ImmutableArray<GenerateHandlerAttributeData> attributesData)
    {
        stringWriter.WriteLine();

        stringWriter.WriteIndentation(2);
        stringWriter.WriteLine("public void RegisterDelegateHandler(global::NetCord.Hosting.AspNetCore.IDelegateWebhookEventHandlerBase handler)");

        stringWriter.WriteIndentation(2);
        stringWriter.Write("{");

        int i = 0;
        foreach (var group in attributesData.GroupBy(e => e.EventArgs, SymbolEqualityComparer.Default))
        {
            var eventArgs = (INamedTypeSymbol)group.Key!;

            stringWriter.WriteLine();

            stringWriter.WriteIndentation(3);
            stringWriter.Write("if (handler is global::NetCord.Hosting.AspNetCore.IDelegateWebhookEventHandler<");

            stringWriter.Write(eventArgs.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));

            stringWriter.Write("> delegateWebhookEventHandler");

            stringWriter.Write(i);
            stringWriter.WriteLine(")");

            stringWriter.WriteIndentation(3);
            stringWriter.WriteLine("{");

            stringWriter.WriteIndentation(4);
            stringWriter.Write("switch (delegateWebhookEventHandler");
            stringWriter.Write(i);
            stringWriter.WriteLine(".RawName)");

            stringWriter.WriteIndentation(4);
            stringWriter.WriteLine("{");

            foreach (var attributeData in group)
            {
                stringWriter.WriteIndentation(5);
                stringWriter.Write("case ");
                if (attributeData.RawEventName is null)
                    stringWriter.WriteLine("null:");
                else
                {
                    stringWriter.Write("\"");
                    stringWriter.Write(attributeData.RawEventName);
                    stringWriter.WriteLine("\":");
                }

                stringWriter.WriteIndentation(6);
                stringWriter.Write(ToInternalName(attributeData.EventName));
                stringWriter.Write(".Add(delegateWebhookEventHandler");
                stringWriter.Write(i);
                stringWriter.WriteLine(".HandleAsync);");

                stringWriter.WriteIndentation(6);
                stringWriter.WriteLine("break;");
            }

            stringWriter.WriteIndentation(4);
            stringWriter.WriteLine("}");

            stringWriter.WriteIndentation(4);
            stringWriter.WriteLine("return;");

            stringWriter.WriteIndentation(3);
            stringWriter.WriteLine("}");

            i++;
        }

        stringWriter.WriteIndentation(2);
        stringWriter.WriteLine("}");
    }

    private void WriteRegisterClassHandlerMethod(StringWriter stringWriter, ImmutableArray<GenerateHandlerAttributeData> attributesData)
    {
        stringWriter.WriteLine();

        stringWriter.WriteIndentation(2);
        stringWriter.WriteLine("public void RegisterClassHandler(global::NetCord.Hosting.AspNetCore.IWebhookEventHandler handler)");

        stringWriter.WriteIndentation(2);
        stringWriter.Write("{");

        int attributeCount = attributesData.Length;

        for (int i = 0; i < attributeCount; i++)
        {
            var attributeData = attributesData[i];

            stringWriter.WriteLine();

            stringWriter.WriteIndentation(3);
            stringWriter.Write("if (handler is global::NetCord.Hosting.AspNetCore.I");
            stringWriter.Write(attributeData.EventName);
            stringWriter.Write("WebhookEventHandler webhookEventHandler");
            stringWriter.Write(i);
            stringWriter.WriteLine(")");

            stringWriter.WriteIndentation(4);
            stringWriter.Write(ToInternalName(attributeData.EventName));
            stringWriter.Write(".Add(webhookEventHandler");
            stringWriter.Write(i);
            stringWriter.WriteLine(".HandleAsync);");
        }

        stringWriter.WriteIndentation(2);
        stringWriter.WriteLine("}");
    }

    private void WriteStorageBuilderBuildMethod(StringWriter stringWriter, ImmutableArray<GenerateHandlerAttributeData> attributesData)
    {
        stringWriter.WriteLine();

        stringWriter.WriteIndentation(2);
        stringWriter.WriteLine("public global::NetCord.Hosting.AspNetCore.WebhookEventHandler.Storage Build()");

        stringWriter.WriteIndentation(2);
        stringWriter.WriteLine("{");

        stringWriter.WriteIndentation(3);
        stringWriter.WriteLine("return new()");

        stringWriter.WriteIndentation(3);
        stringWriter.WriteLine("{");

        int attributeCount = attributesData.Length;
        for (int i = 0; i < attributeCount; i++)
        {
            var attributeData = attributesData[i];

            var internalName = ToInternalName(attributeData.EventName);

            stringWriter.WriteIndentation(4);
            stringWriter.Write(internalName);
            stringWriter.Write(" = [.. ");
            stringWriter.Write(internalName);
            stringWriter.WriteLine("],");
        }

        stringWriter.WriteIndentation(3);
        stringWriter.WriteLine("};");

        stringWriter.WriteIndentation(2);
        stringWriter.WriteLine("}");
    }

    private void WriteStorage(StringWriter stringWriter, ImmutableArray<GenerateHandlerAttributeData> attributesData)
    {
        stringWriter.WriteLine();

        stringWriter.WriteIndentation(1);
        stringWriter.WriteLine("partial class Storage");

        stringWriter.WriteIndentation(1);
        stringWriter.Write("{");

        WriteStorageFields(stringWriter, attributesData);

        stringWriter.WriteIndentation(1);
        stringWriter.WriteLine("}");
    }

    private void WriteStorageFields(StringWriter stringWriter, ImmutableArray<GenerateHandlerAttributeData> attributesData)
    {
        foreach (var attributeData in attributesData)
        {
            stringWriter.WriteLine();

            stringWriter.WriteIndentation(2);
            stringWriter.Write("internal required global::System.Func<");
            stringWriter.Write(attributeData.EventArgs.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
            stringWriter.Write(", global::System.Threading.Tasks.ValueTask>[] ");
            stringWriter.Write(ToInternalName(attributeData.EventName));
            stringWriter.WriteLine(";");
        }
    }

    private void WriteHandleEventAsyncMethod(StringWriter stringWriter, ImmutableArray<GenerateHandlerAttributeData> attributesData)
    {
        stringWriter.WriteLine();

        stringWriter.WriteIndentation(1);
        stringWriter.WriteLine("private global::System.Threading.Tasks.ValueTask HandleEventAsync(global::NetCord.Rest.JsonModels.JsonWebhookEventArgs data)");

        stringWriter.WriteIndentation(1);
        stringWriter.WriteLine("{");

        stringWriter.WriteIndentation(2);
        stringWriter.WriteLine("return data.Event!.Type switch");

        stringWriter.WriteIndentation(2);
        stringWriter.Write("{");

        foreach (var attributeData in attributesData)
        {
            stringWriter.WriteLine();

            stringWriter.WriteIndentation(3);
            if (attributeData.RawEventName is null)
                stringWriter.Write("_ => ");
            else
            {
                stringWriter.Write("\"");
                stringWriter.Write(attributeData.RawEventName);
                stringWriter.Write("\" => ");
            }

            stringWriter.Write("InvokeHandlersAsync(_storage.");
            stringWriter.Write(ToInternalName(attributeData.EventName));
            stringWriter.Write(", () => new ");
            stringWriter.Write(attributeData.EventArgs.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
            if (attributeData.EventArgs.Constructors.First().Parameters.Length is 2)
                stringWriter.Write("(data, _client)),");
            else
                stringWriter.Write("(data)),");
        }

        stringWriter.WriteLine();

        stringWriter.WriteIndentation(2);
        stringWriter.WriteLine("};");

        stringWriter.WriteIndentation(1);
        stringWriter.WriteLine("}");
    }

    private static Span<char> ToInternalName(string name)
    {
        Span<char> copy = new char[name.Length + 1];
        copy[0] = '_';
        name.AsSpan(1).CopyTo(copy[2..]);
        copy[1] = char.ToLowerInvariant(name[0]);
        return copy;
    }
}
