using System.Xml;

using Microsoft.CodeAnalysis;

namespace Shared;

public static class TextWriterExtensions
{
    private const string Indentation = "    ";

    private const int IndentationLength = 4;

    public static unsafe void Write(this TextWriter writer, ReadOnlySpan<char> value)
    {
        if (writer is StringWriter stringWriter)
        {
            fixed (char* ptr = value)
                stringWriter.GetStringBuilder().Append(ptr, value.Length);
        }
        else
            writer.Write(value.ToString());
    }

    public static void WriteNamespace(this TextWriter writer, ITypeSymbol typeSymbol)
    {
        var containingNamespace = typeSymbol.ContainingNamespace;
        if (containingNamespace.IsGlobalNamespace)
            return;

        writer.Write("namespace ");
        writer.Write(containingNamespace.ToDisplayString());
        writer.WriteLine(";");
    }

    public static void WriteTypeDeclaration(this TextWriter writer, ITypeSymbol typeSymbol)
    {
        writer.Write("partial ");
        writer.Write(typeSymbol switch
        {
            { TypeKind: TypeKind.Interface } => "interface ",
            { IsReferenceType: true, IsRecord: false } => "class ",
            { IsReferenceType: true, IsRecord: true } => "record ",
            { IsValueType: true, IsRecord: false } => "struct ",
            { IsValueType: true, IsRecord: true } => "record struct ",
            _ => throw new ArgumentException($"Unsupported type kind: {typeSymbol.TypeKind}", nameof(typeSymbol)),
        });
        writer.WriteLine(typeSymbol.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat));
    }

    public static void WriteInheritDoc(this TextWriter writer, ISymbol symbol, int indentation)
    {
        writer.WriteIndentation(indentation);
        writer.Write("/// <inheritdoc cref=\"");
        writer.Write(symbol.GetDocumentationCommentId());
        writer.WriteLine("\" />");
    }

    public static void CopyXmlComment(this TextWriter writer, ISymbol symbol, Func<XmlNode, bool> predicate, int indentation)
    {
        var comment = symbol.GetDocumentationCommentXml();
        if (string.IsNullOrEmpty(comment))
            return;

        XmlDocument xmlDocument = new();
        xmlDocument.LoadXml(comment);

        foreach (XmlNode xmlNode in xmlDocument.DocumentElement.ChildNodes)
        {
            if (!predicate(xmlNode))
                continue;

            using StringReader stringReader = new(xmlNode.OuterXml);
            string? line;
            while ((line = stringReader.ReadLine()) is not null)
            {
                writer.WriteIndentation(indentation);
                writer.Write("/// ");
                if (line.StartsWith(Indentation))
                    writer.Write(line.AsSpan(IndentationLength));
                else
                    writer.Write(line);

                writer.WriteLine();
            }
        }
    }

    public static void WriteAutoGeneratedComment(this TextWriter writer)
    {
        writer.WriteLine("// <auto-generated/>");
    }

    public static void WriteNullableDirective(this TextWriter writer)
    {
        writer.WriteLine("#nullable enable");
    }

    public static void WriteIndentation(this TextWriter writer, int indentation)
    {
        for (int i = 0; i < indentation; i++)
            writer.Write(Indentation);
    }
}
