using Microsoft.CodeAnalysis;

namespace Shared;

public static class TextWriterExtensions
{
    private const string Indentation = "    ";

    private const int IndentationLength = 4;

    public static unsafe void Write(this TextWriter writer, ReadOnlySpan<char> value)
    {
        if (writer is StringWriter stringWriter)
        {
            fixed (char* ptr = value)
                stringWriter.GetStringBuilder().Append(ptr, value.Length);
        }
        else
            writer.Write(value.ToString());
    }

    public static void WriteNamespace(this TextWriter writer, ITypeSymbol typeSymbol)
    {
        var containingNamespace = typeSymbol.ContainingNamespace;
        if (containingNamespace.IsGlobalNamespace)
            return;

        writer.Write("namespace ");
        writer.Write(containingNamespace.ToDisplayString());
        writer.WriteLine(";");
    }

    public static void WriteTypeDeclaration(this TextWriter writer, ITypeSymbol typeSymbol)
    {
        writer.Write("partial ");
        writer.Write(typeSymbol switch
        {
            { TypeKind: TypeKind.Interface } => "interface ",
            { IsReferenceType: true, IsRecord: false } => "class ",
            { IsReferenceType: true, IsRecord: true } => "record ",
            { IsValueType: true, IsRecord: false } => "struct ",
            { IsValueType: true, IsRecord: true } => "record struct ",
            _ => throw new ArgumentException($"Unsupported type kind: {typeSymbol.TypeKind}", nameof(typeSymbol)),
        });
        writer.WriteLine(typeSymbol.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat));
    }

    public static void WriteInheritDoc(this TextWriter writer, ISymbol symbol)
    {
        writer.Write("/// <inheritdoc cref=\"");
        writer.Write(symbol.GetDocumentationCommentId());
        writer.WriteLine("\" />");
    }

    public static void WriteAutoGeneratedComment(this TextWriter writer)
    {
        writer.WriteLine("// <auto-generated/>");
    }

    public static void WriteNullableDirective(this TextWriter writer)
    {
        writer.WriteLine("#nullable enable");
    }
}
