namespace NetCord;

[Flags]
public enum Permission : ulong
{
    CreateInstantInvite = (ulong)1 << 0,
    KickUsers = (ulong)1 << 1,
    BanUsers = (ulong)1 << 2,
    Administrator = (ulong)1 << 3,
    ManageChannels = (ulong)1 << 4,
    ManageGuild = (ulong)1 << 5,
    AddReactions = (ulong)1 << 6,
    ViewAuditLog = (ulong)1 << 7,
    PrioritySpeaker = (ulong)1 << 8,
    Stream = (ulong)1 << 9,
    ViewChannel = (ulong)1 << 10,
    SendMessages = (ulong)1 << 11,
    SendTtsMessages = (ulong)1 << 12,
    ManageMessages = (ulong)1 << 13,
    EmbedLinks = (ulong)1 << 14,
    AttachFiles = (ulong)1 << 15,
    ReadMessageHistory = (ulong)1 << 16,
    MentionEveryone = (ulong)1 << 17,
    UseExternalEmojis = (ulong)1 << 18,
    ViewGuildInsights = (ulong)1 << 19,
    Connect = (ulong)1 << 20,
    Speak = (ulong)1 << 21,
    MuteUsers = (ulong)1 << 22,
    DeafenUsers = (ulong)1 << 23,
    MoveUsers = (ulong)1 << 24,
    UseVoiceActivityDetection = (ulong)1 << 25,
    ChangeNickname = (ulong)1 << 26,
    ManageNicknames = (ulong)1 << 27,
    ManageRoles = (ulong)1 << 28,
    ManageWebhooks = (ulong)1 << 29,
    ManageEmojisAndStickers = (ulong)1 << 30,
    UseApplicationCommands = (ulong)1 << 31,
    RequestToSpeak = (ulong)1 << 32,
    ManageEvents = (ulong)1 << 33,
    ManageThreads = (ulong)1 << 34,
    CreatePublicThreads = (ulong)1 << 35,
    CreatePrivateThreads = (ulong)1 << 36,
    UseExternalStickers = (ulong)1 << 37,
    SendMessagesInThreads = (ulong)1 << 38,
    StartEmbeddedActivities = (ulong)1 << 39,
    ModerateUsers = (ulong)1 << 40,
}