using System.CodeDom.Compiler;
using System.Text;

using HandlerGenerator.Common;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

using Shared;

namespace HandlerGenerator.HttpInteraction;

[Generator(LanguageNames.CSharp)]
public class Generator : IIncrementalGenerator
{
    private const string Namespace = "NetCord.Hosting.AspNetCore";

    private const string HandlerBaseTypeName = "global::NetCord.Hosting.IHttpInteractionHandler";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(context =>
        {
            context.AddSource("HttpInteractionHandlerInvoker.g.cs", SourceText.From(GenerateHttpInteractionHandlerInvoker(), Encoding.UTF8));
        });
    }

    private static void Setup(IndentedTextWriter writer)
    {
        writer.WriteAutoGeneratedComment();
        writer.WriteLine();

        writer.WriteNullableDirective();
        writer.WriteLine();

        writer.Write("namespace ");
        writer.Write(Namespace);
        writer.WriteLine(";");
    }

    private string GenerateHttpInteractionHandlerInvoker()
    {
        StringWriter stringWriter = new();
        IndentedTextWriter writer = new(stringWriter);

        Setup(writer);

        WriteHttpInteractionHandlerInvoker(writer);

        return stringWriter.ToString();
    }

    private void WriteHttpInteractionHandlerInvoker(IndentedTextWriter writer)
    {
        writer.WriteLine();

        writer.WriteLine("partial class HttpInteractionHandlerInvoker");

        writer.Write("{");
        writer.Indent++;

        WriteRegisterHandlerMethods(writer);

        writer.Indent--;
        writer.WriteLine("}");
    }

    private void WriteRegisterHandlerMethods(IndentedTextWriter writer)
    {
        WriteCreateDelegateHandlerMethod(writer);

        WriteCreateClassHandlerMethod(writer);
    }

    private void WriteCreateDelegateHandlerMethod(IndentedTextWriter writer)
    {
        writer.WriteLine();

        writer.WriteLine("public static global::System.Func<global::NetCord.Interaction, global::System.Threading.Tasks.ValueTask> CreateDelegateInvokeDelegate(global::NetCord.Hosting.DelegateHandlerMetadata handlerMetadata, IServiceProvider services)");

        writer.WriteLine("{");
        writer.Indent++;

        DelegateHandlerInvocationHelper.WriteDelegateHandlerInvocationDelegate(
            writer,
            [new("interaction", "global::NetCord.Interaction")]);

        writer.WriteLine("return handler;");

        writer.Indent--;
        writer.WriteLine("}");
    }

    private void WriteCreateClassHandlerMethod(IndentedTextWriter writer)
    {
        writer.WriteLine();

        writer.WriteLine("public static global::System.Func<global::NetCord.Interaction, global::System.Threading.Tasks.ValueTask> CreateClassInvokeDelegate(global::NetCord.Hosting.ClassHandlerMetadata handlerMetadata, IServiceProvider services)");

        writer.WriteLine("{");
        writer.Indent++;

        writer.WriteLine("var handlerType = handlerMetadata.HandlerType;");

        writer.WriteLine("var instanceFactory = handlerMetadata.InstanceFactory;");

        ClassHandlerInvocationHelper.WriteClassHandlerInvocationDelegate(
            writer,
            HandlerBaseTypeName,
            [new("interaction", "global::NetCord.Interaction")]);

        writer.WriteLine("return handler;");

        writer.Indent--;
        writer.WriteLine("}");
    }
}
