namespace NetCord.Rest;

/// <summary>
/// Represents a message sent in a channel within Discord.
/// </summary>
public partial class RestMessage : ClientEntity, IJsonModel<NetCord.JsonModels.JsonMessage>
{
    NetCord.JsonModels.JsonMessage IJsonModel<NetCord.JsonModels.JsonMessage>.JsonModel => _jsonModel;
    private protected readonly NetCord.JsonModels.JsonMessage _jsonModel;

    public RestMessage(NetCord.JsonModels.JsonMessage jsonModel, RestClient client) : base(client)
    {
        _jsonModel = jsonModel;

        var guildUser = jsonModel.GuildUser;
        if (guildUser is null)
            Author = new(jsonModel.Author!, client);
        else
        {
            guildUser.User = jsonModel.Author!;
            Author = new GuildUser(guildUser, jsonModel.GuildId.GetValueOrDefault(), client);
        }

        MentionedUsers = jsonModel.MentionedUsers!.Select(u =>
        {
            var guildUser = u.GuildUser;
            if (guildUser is null)
                return new User(u, client);

            guildUser.User = u;
            return new GuildUser(guildUser, jsonModel.GuildId.GetValueOrDefault(), client);
        }).ToArray();

        MentionedChannels = jsonModel.MentionedChannels.SelectOrEmpty(c => new GuildChannelMention(c)).ToArray();
        Attachments = jsonModel.Attachments!.Select(a => Attachment.CreateFromJson(a, client)).ToArray();
        Embeds = jsonModel.Embeds!.Select(e => new Embed(e)).ToArray();
        Reactions = jsonModel.Reactions.SelectOrEmpty(r => new MessageReaction(r)).ToArray();

        var activity = jsonModel.Activity;
        if (activity is not null)
            Activity = new(activity);

        var application = jsonModel.Application;
        if (application is not null)
            Application = new(application, client);

        var messageReference = jsonModel.MessageReference;
        if (messageReference is not null)
        {
            MessageReference = new(messageReference);

            MessageSnapshots = jsonModel.MessageSnapshots.SelectOrEmpty(s => new MessageSnapshot(s, messageReference.GuildId, client)).ToArray();
        }
        else
            MessageSnapshots = [];

        var referencedMessage = jsonModel.ReferencedMessage;
        if (referencedMessage is not null)
            ReferencedMessage = new(referencedMessage, client);

        var interactionMetadata = jsonModel.InteractionMetadata;
        if (interactionMetadata is not null)
            InteractionMetadata = new(interactionMetadata, client);

#pragma warning disable CS0618 // Type or member is obsolete
        var interaction = jsonModel.Interaction;
        if (interaction is not null)
            Interaction = new(interaction, client);
#pragma warning restore CS0618 // Type or member is obsolete

        var startedThread = jsonModel.StartedThread;
        if (startedThread is not null)
            StartedThread = GuildThread.CreateFromJson(startedThread, client);

        Components = jsonModel.Components.SelectOrEmpty(IMessageComponent.CreateFromJson).ToArray();
#pragma warning disable CS0618 // Type or member is obsolete
        Stickers = jsonModel.Stickers.SelectOrEmpty(s => new MessageSticker(s, client)).ToArray();
#pragma warning restore CS0618 // Type or member is obsolete

        var roleSubscriptionData = jsonModel.RoleSubscriptionData;
        if (roleSubscriptionData is not null)
            RoleSubscriptionData = new(roleSubscriptionData);

        var resolvedData = jsonModel.ResolvedData;
        if (resolvedData is not null)
            ResolvedData = new(resolvedData, jsonModel.GuildId, client);

        var poll = jsonModel.Poll;
        if (poll is not null)
            Poll = new(poll);

        var call = jsonModel.Call;
        if (call is not null)
            Call = new(call);

        var theme = jsonModel.SharedClientTheme;
        if (theme is not null)
            SharedClientTheme = new(theme);
    }

    /// <summary>
    /// The ID of the message.
    /// </summary>
    public override ulong Id => _jsonModel.Id;

    /// <summary>
    /// The ID of the channel the message was sent in.
    /// </summary>
    public ulong ChannelId => _jsonModel.ChannelId;

    /// <summary>
    /// The <see cref="User"/> object of the message's author.
    /// </summary>
    /// <remarks>
    /// If the message is generated by a <see cref="Webhook"/>, the <see cref="User"/> object will correspond to the webhook's ID, username, and avatar.
    /// </remarks>
    public User Author { get; }

    /// <summary>
    /// The text contents of the message.
    /// </summary>
    public string Content => _jsonModel.Content!;

    /// <summary>
    /// If the message has been edited, contains the timestamp of the latest edit, otherwise <see langword="null"/>.
    /// </summary>
    public DateTimeOffset? EditedAt => _jsonModel.EditedAt;

    /// <summary>
    /// Whether the message was a Text-To-Speech message.
    /// </summary>
    public bool IsTts => _jsonModel.IsTts.GetValueOrDefault();

    /// <summary>
    /// Whether the message mentions <see langword="@everyone"/>.
    /// </summary>
    public bool MentionEveryone => _jsonModel.MentionEveryone.GetValueOrDefault();

    /// <summary>
    /// A list of users specifically mentioned in the message.
    /// </summary>
    public IReadOnlyList<User> MentionedUsers { get; }

    /// <summary>
    /// A list of IDs corresponding to roles specifically mentioned in the message.
    /// </summary>
    public IReadOnlyList<ulong> MentionedRoleIds => _jsonModel.MentionedRoleIds!;

    /// <summary>
    /// A list of <see cref="GuildChannelMention"/> objects indexed by their IDs, containing channels specifically mentioned in the message.
    /// </summary>
    /// <remarks>
    /// <para>This list is only populated for messages with the <see cref="MessageFlags.Crossposted"/> flag set.</para>
    /// <para>Only text channels visible to everyone in a lurkable guild will ever be included.</para>
    /// </remarks>
    public IReadOnlyList<GuildChannelMention> MentionedChannels { get; }

    /// <summary>
    /// A list containing the message's attachments.
    /// </summary>
    public IReadOnlyList<Attachment> Attachments { get; }

    /// <summary>
    /// A list of <see cref="Embed"/> objects, representing any embedded content present in the message.
    /// </summary>
    public IReadOnlyList<Embed> Embeds { get; }

    /// <summary>
    /// A list of <see cref="MessageReaction"/> objects, representing all reactions to the message.
    /// </summary>
    public IReadOnlyList<MessageReaction> Reactions { get; }

    /// <summary>
    /// Used for validating that a message was sent.
    /// </summary>
    public string? Nonce => _jsonModel.Nonce;

    /// <summary>
    /// Whether this message is pinned in a channel.
    /// </summary>
    public bool IsPinned => _jsonModel.IsPinned.GetValueOrDefault();

    /// <summary>
    /// If the message was generated by a <see cref="Webhook"/>, contains the webhook's ID, otherwise <see langword="null"/>.
    /// </summary>
    public ulong? WebhookId => _jsonModel.WebhookId;

    /// <summary>
    /// The type of the message.
    /// </summary>
    public MessageType Type => _jsonModel.Type.GetValueOrDefault();

    /// <summary>
    /// Sent with Rich Presence-related chat embeds.
    /// </summary>
    public MessageActivity? Activity { get; }

    /// <summary>
    /// Sent with Rich Presence-related chat embeds.
    /// </summary>
    public Application? Application { get; }

    /// <summary>
    /// If the message is an <see cref="NetCord.Interaction"/> response/followup or an application-owned <see cref="Webhook"/>, the ID of the <see cref="NetCord.Application"/>.
    /// </summary>
    public ulong? ApplicationId => _jsonModel.ApplicationId;

    /// <summary>
    /// A <see cref="MessageFlags"/> object indicating the message's applied flags.
    /// </summary>
    public MessageFlags Flags => _jsonModel.Flags.GetValueOrDefault();

    /// <summary>
    /// Contains data showing the source of a crosspost, channel follow add, pin, or message reply.
    /// </summary>
    public MessageReference? MessageReference { get; }

    /// <summary>
    /// A list of messages associated with the message reference.
    /// </summary>
    public IReadOnlyList<MessageSnapshot> MessageSnapshots { get; }

    /// <summary>
    /// The message associated with the <see cref="MessageReference"/>.
    /// </summary>
    /// <remarks>
    /// This field is only returned for messages with a <see cref="MessageType"/> of <see cref="MessageType.Reply"/> or <see cref="MessageType.ThreadStarterMessage"/>. If the message is a reply but the <see cref="ReferencedMessage"/> field is not present, the backend did not attempt to fetch the message that was being replied to, so its state is unknown. If the field exists but is null, the referenced message was deleted.
    /// </remarks>
    public RestMessage? ReferencedMessage { get; }

    /// <summary>
    /// Sent if the message is sent as a result of an interaction.
    /// </summary>
    public MessageInteractionMetadata? InteractionMetadata { get; }

    /// <summary>
    /// Sent if the message is a response to an interaction.
    /// </summary>
    [Obsolete($"Replaced by '{nameof(InteractionMetadata)}'")]
    public MessageInteraction? Interaction { get; }

    /// <summary>
    /// The <see cref="GuildThread"/> that was started from this message, if any.
    /// </summary>
    public GuildThread? StartedThread { get; }

    /// <summary>
    /// A list of <see cref="IMessageComponent"/> objects, contains components like <see cref="Button"/>s, <see cref="ActionRow"/>s, or other interactive components if any are present.
    /// </summary>
    public IReadOnlyList<IMessageComponent> Components { get; }

    /// <summary>
    /// A list of stickers sent within the message.
    /// </summary>
    [Obsolete("Deprecated by Discord.")]
    public IReadOnlyList<MessageSticker> Stickers { get; }

    /// <summary>
    /// A generally increasing integer (there may be gaps or duplicates) that represents the approximate position of the message in a <see cref="GuildThread"/>.
    /// </summary>
    /// <remarks>
    /// It can be used to estimate the relative position of the message in a thread in tandem with the <see cref="GuildThread.TotalMessageSent"/> property of the parent thread.
    /// </remarks>
    public int? Position => _jsonModel.Position;

    /// <summary>
    /// Contains information about the role subscription purchase or renewal that prompted this <see cref="MessageType.RoleSubscriptionPurchase"/> message.
    /// </summary>
    public RoleSubscriptionData? RoleSubscriptionData { get; }

    /// <summary>
    /// Contains information about the <see cref="User"/>, <see cref="GuildUser"/>, <see cref="IGuildChannel"/>, and <see cref="Role"/> objects in the message's auto-populated selection menus.
    /// </summary>
    public InteractionResolvedData? ResolvedData { get; }

    /// <summary>
    /// The message's contained poll, if it has one, otherwise <see langword="null"/>.
    /// </summary>
    /// <remarks>
    /// This is always <see langword="null"/> if the <see cref="Gateway.GatewayIntents.MessageContent"/> intent is not set.
    /// </remarks>
    public MessagePoll? Poll { get; }

    /// <summary>
    /// The call associated with the message, if any.
    /// </summary>
    public MessageCall? Call { get; }

    /// <summary>
    /// The custom client-side theme shared in the message, if any.
    /// </summary>
    public SharedClientTheme? SharedClientTheme { get; }

    /// <summary>
    /// Replies to the message, returning the resulting reply.
    /// </summary>
    /// <param name="replyMessage">The message to reply with.</param>
    /// <param name="properties">Optional properties to customize the request, can be <see langword="null"/>.</param>
    /// <param name="cancellationToken">A token that can be used to cancel the operation before it completes.</param>
    public Task<RestMessage> ReplyAsync(ReplyMessageProperties replyMessage, RestRequestProperties? properties = null, CancellationToken cancellationToken = default)
        => SendAsync(replyMessage.ToMessageProperties(Id), properties, cancellationToken);
}
