using System.CodeDom.Compiler;
using System.Collections.Immutable;
using System.Globalization;
using System.Text;

using HandlerGenerator.Common;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

using Shared;

namespace HandlerGenerator.Webhook;

[Generator(LanguageNames.CSharp)]
public class Generator : IIncrementalGenerator
{
    private const string Namespace = "NetCord.Hosting.AspNetCore";

    private const string HandlerBaseTypeName = "global::NetCord.Hosting.AspNetCore.IWebhookHandler";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(context =>
        {
            context.AddSource("GenerateHandlerAttribute.g.cs", SourceText.From(
                """
                #nullable enable

                namespace NetCord.Hosting.AspNetCore;

                [AttributeUsage(AttributeTargets.Class, AllowMultiple = true)]
                internal class GenerateHandlerAttribute(string? rawEventName, Type? eventArgs) : Attribute
                {
                    public string? RawEventName => rawEventName;

                    public Type? EventArgs => eventArgs;
                }

                """, Encoding.UTF8));
        });

        var attributesData = context.SyntaxProvider.ForAttributeWithMetadataName("NetCord.Hosting.AspNetCore.GenerateHandlerAttribute",
                                                            (syntaxNode, cancellationToken) => syntaxNode is ClassDeclarationSyntax,
                                                            (context, cancellationToken) =>
                                                            {
                                                                return context.Attributes
                                                                    .Where(a => a.ConstructorArguments.Length >= 2)
                                                                    .Select(a =>
                                                                    {
                                                                        var constructorArguments = a.ConstructorArguments;
                                                                        return new GenerateHandlerAttributeData((string?)constructorArguments[0].Value, (INamedTypeSymbol)constructorArguments[1].Value!);
                                                                    });
                                                            })
            .SelectMany((data, cancellationToken) => data)
            .Collect();

        context.RegisterSourceOutput(attributesData, (context, attributesData) =>
        {
            context.AddSource("WebhookEvent.g.cs", SourceText.From(GenerateEvents(attributesData), Encoding.UTF8));

            context.AddSource("WebhookHandlerInterfaces.g.cs", SourceText.From(GenerateHandlerInterfaces(attributesData), Encoding.UTF8));

            context.AddSource("WebhookEventHandlerInvoker.g.cs", SourceText.From(GenerateWebhookEventHandlerInvoker(attributesData), Encoding.UTF8));
        });
    }

    private class GenerateHandlerAttributeData(string? rawEventName, INamedTypeSymbol? eventArgs)
    {
        public string? RawEventName => rawEventName;

        public string EventName { get; } = GetEventName(rawEventName);

        public INamedTypeSymbol? EventArgs => eventArgs;

        private static string GetEventName(string? rawEventName)
        {
            if (rawEventName is null)
                return "UnknownEvent";

            var textInfo = CultureInfo.InvariantCulture.TextInfo;

            var result = textInfo.ToLower(rawEventName);

            result = textInfo.ToTitleCase(result);

            result = result.Replace("_", string.Empty);

            return result;
        }
    }

    private static void Setup(IndentedTextWriter writer)
    {
        writer.WriteAutoGeneratedComment();
        writer.WriteLine();

        writer.WriteNullableDirective();
        writer.WriteLine();

        writer.Write("namespace ");
        writer.Write(Namespace);
        writer.WriteLine(";");
    }

    private string GenerateEvents(ImmutableArray<GenerateHandlerAttributeData> attributesData)
    {
        StringWriter stringWriter = new();
        IndentedTextWriter writer = new(stringWriter);

        Setup(writer);

        WriteEventsEnum(writer, attributesData);

        WriteEvents(writer, attributesData);

        return stringWriter.ToString();
    }

    private void WriteEvents(IndentedTextWriter writer, ImmutableArray<GenerateHandlerAttributeData> attributesData)
    {
        writer.WriteLine();

        writer.WriteLine("partial class WebhookEvent");
        writer.Write("{");
        writer.Indent++;

        foreach (var attributeData in attributesData)
        {
            var eventArgs = attributeData.EventArgs;

            writer.WriteLine();

            if (eventArgs is not null)
                writer.WriteInheritDoc(eventArgs, 1);

            writer.Write("public static global::");
            writer.Write(Namespace);
            writer.Write(".WebhookEvent");

            if (eventArgs is not null)
            {
                writer.Write("<");
                writer.Write(eventArgs.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
                writer.Write("> ");
            }

            var eventName = attributeData.EventName;

            writer.Write(eventName);
            writer.Write(" => new(global::NetCord.Hosting.AspNetCore.WebhookEventId.");

            writer.Write(eventName);

            writer.WriteLine(");");
        }

        writer.Indent--;
        writer.WriteLine("}");
    }

    private void WriteEventsEnum(IndentedTextWriter writer, ImmutableArray<GenerateHandlerAttributeData> attributesData)
    {
        writer.WriteLine();

        writer.WriteLine("internal enum WebhookEventId : byte");

        writer.WriteLine("{");
        writer.Indent++;

        int attributeCount = attributesData.Length;
        for (int i = 0; i < attributeCount; i++)
        {
            var attributeData = attributesData[i];

            writer.Write(attributeData.EventName);
            writer.WriteLine(",");
        }

        writer.Indent--;
        writer.WriteLine("}");
    }

    private string GenerateHandlerInterfaces(ImmutableArray<GenerateHandlerAttributeData> attributesData)
    {
        StringWriter stringWriter = new();
        IndentedTextWriter writer = new(stringWriter);

        Setup(writer);

        WriteHandlerInterfaces(writer, attributesData);

        return stringWriter.ToString();
    }

    private void WriteHandlerInterfaces(IndentedTextWriter writer, ImmutableArray<GenerateHandlerAttributeData> attributesData)
    {
        foreach (var attributeData in attributesData)
        {
            var eventArgs = attributeData.EventArgs;

            writer.WriteLine();

            if (eventArgs is not null)
                writer.WriteInheritDoc(eventArgs, 0);

            writer.Write("public interface I");
            writer.Write(attributeData.EventName);
            writer.Write("WebhookHandler : ");
            writer.WriteLine(HandlerBaseTypeName);

            writer.WriteLine("{");
            writer.Indent++;

            writer.Write("public global::System.Threading.Tasks.ValueTask HandleAsync(");

            if (eventArgs is not null)
            {
                writer.Write(eventArgs.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
                writer.Write(" arg");
            }

            writer.WriteLine(");");

            writer.Indent--;
            writer.WriteLine("}");
        }
    }

    private string GenerateWebhookEventHandlerInvoker(ImmutableArray<GenerateHandlerAttributeData> attributesData)
    {
        StringWriter stringWriter = new();
        IndentedTextWriter writer = new(stringWriter);

        Setup(writer);

        WriteWebhookEventHandlerInvoker(writer, attributesData);

        return stringWriter.ToString();
    }

    private void WriteWebhookEventHandlerInvoker(IndentedTextWriter writer, ImmutableArray<GenerateHandlerAttributeData> attributesData)
    {
        writer.WriteLine();

        writer.WriteLine("partial class WebhookEventHandlerInvoker");

        writer.Write("{");
        writer.Indent++;

        WriteStorageBuilder(writer, attributesData);

        WriteStorage(writer, attributesData);

        WriteHandleEventAsyncMethod(writer, attributesData);

        writer.Indent--;
        writer.WriteLine("}");
    }

    private void WriteStorageBuilder(IndentedTextWriter writer, ImmutableArray<GenerateHandlerAttributeData> attributesData)
    {
        writer.WriteLine();

        writer.WriteLine("partial class StorageBuilder");

        writer.Write("{");
        writer.Indent++;

        WriteStorageBuilderFields(writer, attributesData);

        WriteRegisterDelegateHandlerMethod(writer, attributesData);

        WriteRegisterClassHandlerMethod(writer, attributesData);

        WriteStorageBuilderBuildMethod(writer, attributesData);

        writer.Indent--;
        writer.WriteLine("}");
    }

    private void WriteStorageBuilderFields(IndentedTextWriter writer, ImmutableArray<GenerateHandlerAttributeData> attributesData)
    {
        foreach (var attributeData in attributesData)
        {
            writer.WriteLine();

            writer.Write("private global::System.Collections.Generic.List<global::System.Func<");
            if (attributeData.EventArgs is { } eventArgs)
            {
                writer.Write(eventArgs.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
                writer.Write(", ");
            }
            writer.Write("global::System.Threading.Tasks.ValueTask>> ");
            writer.Write(ToInternalName(attributeData.EventName));
            writer.WriteLine(" = [];");
        }
    }

    private void WriteRegisterDelegateHandlerMethod(IndentedTextWriter writer, ImmutableArray<GenerateHandlerAttributeData> attributesData)
    {
        writer.WriteLine();

        writer.WriteLine("public void RegisterDelegateHandler(global::NetCord.Hosting.DelegateHandlerMetadata<global::NetCord.Hosting.AspNetCore.WebhookEventId> handlerMetadata, IServiceProvider services)");

        writer.WriteLine("{");
        writer.Indent++;

        writer.WriteLine("switch (handlerMetadata.EventId)");

        writer.WriteLine("{");
        writer.Indent++;

        int attributeCount = attributesData.Length;

        for (var i = 0; i < attributeCount; i++)
        {
            var attributeData = attributesData[i];

            writer.Write("case global::NetCord.Hosting.AspNetCore.WebhookEventId.");
            writer.Write(attributeData.EventName);
            writer.WriteLine(":");
            writer.Indent++;

            writer.WriteLine("{");
            writer.Indent++;

            DelegateHandlerInvocationHelper.WriteDelegateHandlerInvocationDelegate(
                writer,
                attributeData.EventArgs is { } arg ? [new("arg", arg)] : []);

            writer.Write(ToInternalName(attributeData.EventName));
            writer.WriteLine(".Add(handler);");

            writer.WriteLine("break;");

            writer.Indent--;
            writer.WriteLine("}");

            writer.Indent--;
        }

        writer.Indent--;
        writer.WriteLine("}");

        writer.Indent--;
        writer.WriteLine("}");
    }

    private void WriteRegisterClassHandlerMethod(IndentedTextWriter writer, ImmutableArray<GenerateHandlerAttributeData> attributesData)
    {
        writer.WriteLine();

        writer.WriteLine("public void RegisterClassHandler(global::NetCord.Hosting.ClassHandlerMetadata handlerMetadata, IServiceProvider services)");

        writer.WriteLine("{");
        writer.Indent++;

        writer.WriteLine("var handlerType = handlerMetadata.HandlerType;");

        writer.WriteLine("var instanceFactory = handlerMetadata.InstanceFactory;");

        int attributeCount = attributesData.Length;

        for (int i = 0; i < attributeCount; i++)
        {
            var attributeData = attributesData[i];

            writer.WriteLine();

            writer.Write("if (typeof(global::NetCord.Hosting.AspNetCore.I");
            writer.Write(attributeData.EventName);
            writer.WriteLine("WebhookHandler).IsAssignableFrom(handlerType))");

            writer.WriteLine("{");
            writer.Indent++;

            ClassHandlerInvocationHelper.WriteClassHandlerInvocationDelegate(
                writer,
                $"global::NetCord.Hosting.AspNetCore.I{attributeData.EventName}WebhookHandler",
                attributeData.EventArgs is { } arg ? [new("arg", arg)] : []);

            writer.Write(ToInternalName(attributeData.EventName));
            writer.WriteLine(".Add(handler);");

            writer.Indent--;
            writer.WriteLine("}");
        }

        writer.Indent--;
        writer.WriteLine("}");
    }

    private void WriteStorageBuilderBuildMethod(IndentedTextWriter writer, ImmutableArray<GenerateHandlerAttributeData> attributesData)
    {
        writer.WriteLine();

        writer.WriteLine("public global::NetCord.Hosting.AspNetCore.WebhookEventHandlerInvoker.Storage Build()");

        writer.WriteLine("{");
        writer.Indent++;

        writer.WriteLine("return new()");

        writer.WriteLine("{");
        writer.Indent++;

        int attributeCount = attributesData.Length;
        for (int i = 0; i < attributeCount; i++)
        {
            var attributeData = attributesData[i];

            var internalName = ToInternalName(attributeData.EventName);

            writer.Write(internalName);
            writer.Write(" = [.. ");
            writer.Write(internalName);
            writer.WriteLine("],");
        }

        writer.Indent--;
        writer.WriteLine("};");

        writer.Indent--;
        writer.WriteLine("}");
    }

    private void WriteStorage(IndentedTextWriter writer, ImmutableArray<GenerateHandlerAttributeData> attributesData)
    {
        writer.WriteLine();

        writer.WriteLine("partial class Storage");

        writer.Write("{");
        writer.Indent++;

        WriteStorageFields(writer, attributesData);

        writer.Indent--;
        writer.WriteLine("}");
    }

    private void WriteStorageFields(IndentedTextWriter writer, ImmutableArray<GenerateHandlerAttributeData> attributesData)
    {
        foreach (var attributeData in attributesData)
        {
            writer.WriteLine();

            writer.Write("internal required global::System.Func<");

            if (attributeData.EventArgs is { } eventArgs)
            {
                writer.Write(eventArgs.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
                writer.Write(", ");
            }

            writer.Write("global::System.Threading.Tasks.ValueTask>[] ");
            writer.Write(ToInternalName(attributeData.EventName));
            writer.WriteLine(";");
        }
    }

    private void WriteHandleEventAsyncMethod(IndentedTextWriter writer, ImmutableArray<GenerateHandlerAttributeData> attributesData)
    {
        writer.WriteLine();

        writer.WriteLine("private global::System.Threading.Tasks.ValueTask HandleEventAsync(global::NetCord.Rest.WebhookEventArgs data)");

        writer.WriteLine("{");
        writer.Indent++;

        writer.WriteLine("return data.Type switch");

        writer.Write("{");
        writer.Indent++;

        foreach (var attributeData in attributesData)
        {
            writer.WriteLine();

            if (attributeData.RawEventName is { } rawEventName)
            {
                writer.Write("\"");
                writer.Write(rawEventName);
                writer.Write("\" => ");
            }
            else
                writer.Write("_ => ");

            writer.Write("InvokeHandlersAsync(_storage.");
            writer.Write(ToInternalName(attributeData.EventName));
            if (attributeData.EventArgs is { } eventArgs)
            {
                writer.Write(", (");
                writer.Write(eventArgs.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
                writer.Write(")data),");
            }
            else
                writer.Write("),");
        }

        writer.WriteLine();

        writer.Indent--;
        writer.WriteLine("};");

        writer.Indent--;
        writer.WriteLine("}");
    }

    private static Span<char> ToInternalName(string name)
    {
        Span<char> copy = new char[name.Length + 1];
        copy[0] = '_';
        name.AsSpan(1).CopyTo(copy[2..]);
        copy[1] = char.ToLowerInvariant(name[0]);
        return copy;
    }
}
