using System.CodeDom.Compiler;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

using Shared;

namespace WebSocketClientEventsGenerator;

[Generator(LanguageNames.CSharp)]
public class WebSocketClientEventsGenerator : IIncrementalGenerator
{
    private const string WebSocketClientName = "WebSocketClient";
    private const string GatewayClientName = "GatewayClient";
    private const string VoiceClientName = "VoiceClient";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var typeSymbols = context.SyntaxProvider
            .CreateSyntaxProvider((node, cancellationToken) => node is ClassDeclarationSyntax { Identifier.Text: WebSocketClientName or GatewayClientName or VoiceClientName },
                                  (context, cancellationToken) => (INamedTypeSymbol)context.SemanticModel.GetDeclaredSymbol(context.Node)!)
            .Collect();

        context.RegisterSourceOutput(typeSymbols, (context, source) =>
        {
            foreach (var typeSymbol in source.Distinct(SymbolEqualityComparer.Default).Cast<INamedTypeSymbol>())
                context.AddSource($"{typeSymbol.Name}.g.cs", SourceText.From(GenerateEvents(typeSymbol), Encoding.UTF8));
        });
    }

    private string GenerateEvents(INamedTypeSymbol typeSymbol)
    {
        StringWriter stringWriter = new();
        IndentedTextWriter writer = new(stringWriter);

        writer.WriteAutoGeneratedComment();
        writer.WriteLine();

        writer.WriteNullableDirective();
        writer.WriteLine();

        writer.Write("namespace ");
        writer.Write(typeSymbol.ContainingNamespace.ToString());
        writer.WriteLine(";");
        writer.WriteLine();

        writer.Write("partial class ");
        writer.WriteLine(typeSymbol.Name);
        writer.WriteLine("{");
        writer.Indent++;

        var events = GetEvents(typeSymbol);

        WriteEvents(writer, events);

        writer.Indent--;
        writer.WriteLine("}");

        return stringWriter.ToString();
    }

    private void WriteEvents(IndentedTextWriter writer, IEventSymbol[] events)
    {
        foreach (var eventSymbol in events)
        {
            var eventType = (INamedTypeSymbol)eventSymbol.Type;

            writer.Write("public partial event ");

            WriteEventType(writer, eventType);

            writer.Write("? ");
            writer.WriteLine(eventSymbol.Name);

            writer.WriteLine("{");
            writer.Indent++;

            writer.WriteLine("add");

            writer.WriteLine("{");
            writer.Indent++;

            writer.Write("AddEventHandler(ref ");

            var internalName = ToInternalName(eventSymbol.Name);

            writer.Write(internalName);
            writer.WriteLine(", value);");

            writer.Indent--;
            writer.WriteLine("}");

            writer.WriteLine("remove");

            writer.WriteLine("{");
            writer.Indent++;

            writer.Write("RemoveEventHandler(ref ");
            writer.Write(internalName);
            writer.WriteLine(", value);");

            writer.Indent--;
            writer.WriteLine("}");

            writer.Indent--;
            writer.WriteLine("}");

            writer.Write("private System.Collections.Immutable.ImmutableList<");
            WriteEventType(writer, eventType);
            writer.Write("> ");
            writer.Write(internalName);
            writer.WriteLine(" = [];");
            writer.WriteLine();
        }
    }

    private static void WriteEventType(IndentedTextWriter writer, INamedTypeSymbol eventType)
    {
        writer.Write(eventType.ContainingNamespace.ToDisplayString());
        writer.Write(".");
        writer.Write(eventType.Name);
        writer.Write("<");

        var typeArguments = eventType.TypeArguments;
        var max = typeArguments.Length - 1;
        for (var i = 0; i < max; i++)
        {
            var typeArgument = typeArguments[i];
            writer.Write(typeArgument.ContainingNamespace.ToDisplayString());
            writer.Write(".");
            writer.Write(typeArgument.Name);

            writer.Write(", ");
        }

        var lastTypeArgument = typeArguments[max];
        writer.Write(lastTypeArgument.ContainingNamespace.ToDisplayString());
        writer.Write(".");
        writer.Write(lastTypeArgument.Name);

        writer.Write(">");
    }

    private static IEventSymbol[] GetEvents(INamedTypeSymbol typeSymbol)
    {
        return [.. typeSymbol.GetMembers().OfType<IEventSymbol>()];
    }

    private static Span<char> ToInternalName(string name)
    {
        Span<char> copy = new char[name.Length + 1];
        copy[0] = '_';
        name.AsSpan(1).CopyTo(copy[2..]);
        copy[1] = char.ToLowerInvariant(name[0]);
        return copy;
    }
}
