using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

using Shared;

namespace WebSocketClientEventsGenerator;

[Generator(LanguageNames.CSharp)]
public class WebSocketClientEventsGenerator : IIncrementalGenerator
{
    private const string WebSocketClientName = "WebSocketClient";
    private const string GatewayClientName = "GatewayClient";
    private const string VoiceClientName = "VoiceClient";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var typeSymbols = context.SyntaxProvider
            .CreateSyntaxProvider((node, cancellationToken) => node is ClassDeclarationSyntax { Identifier.Text: WebSocketClientName or GatewayClientName or VoiceClientName },
                                  (context, cancellationToken) => (INamedTypeSymbol)context.SemanticModel.GetDeclaredSymbol(context.Node)!)
            .Collect();

        context.RegisterSourceOutput(typeSymbols, (context, source) =>
        {
            foreach (var typeSymbol in source.Distinct(SymbolEqualityComparer.Default).Cast<INamedTypeSymbol>())
                context.AddSource($"{typeSymbol.Name}.g.cs", SourceText.From(GenerateEvents(typeSymbol), Encoding.UTF8));
        });
    }

    private string GenerateEvents(INamedTypeSymbol typeSymbol)
    {
        StringWriter stringWriter = new();
        stringWriter.WriteAutoGeneratedComment();
        stringWriter.WriteLine();

        stringWriter.WriteNullableDirective();
        stringWriter.WriteLine();

        stringWriter.Write("namespace ");
        stringWriter.Write(typeSymbol.ContainingNamespace.ToString());
        stringWriter.WriteLine(";");
        stringWriter.WriteLine();

        stringWriter.Write("partial class ");
        stringWriter.WriteLine(typeSymbol.Name);
        stringWriter.WriteLine("{");

        var events = GetEvents(typeSymbol);

        WriteEvents(stringWriter, events);

        stringWriter.WriteLine("}");

        return stringWriter.ToString();
    }

    private void WriteEvents(StringWriter stringWriter, IEventSymbol[] events)
    {
        foreach (var eventSymbol in events)
        {
            var eventType = (INamedTypeSymbol)eventSymbol.Type;

            stringWriter.WriteIndentation(1);
            stringWriter.Write("public partial event ");

            WriteEventType(stringWriter, eventType);

            stringWriter.Write("? ");
            stringWriter.WriteLine(eventSymbol.Name);

            stringWriter.WriteIndentation(1);
            stringWriter.WriteLine("{");

            stringWriter.WriteIndentation(2);
            stringWriter.WriteLine("add");

            stringWriter.WriteIndentation(2);
            stringWriter.WriteLine("{");

            stringWriter.WriteIndentation(3);
            stringWriter.Write("AddEventHandler(ref ");

            var internalName = ToInternalName(eventSymbol.Name);

            stringWriter.Write(internalName);
            stringWriter.WriteLine(", value);");

            stringWriter.WriteIndentation(2);
            stringWriter.WriteLine("}");

            stringWriter.WriteIndentation(2);
            stringWriter.WriteLine("remove");

            stringWriter.WriteIndentation(2);
            stringWriter.WriteLine("{");

            stringWriter.WriteIndentation(3);
            stringWriter.Write("RemoveEventHandler(ref ");
            stringWriter.Write(internalName);
            stringWriter.WriteLine(", value);");

            stringWriter.WriteIndentation(2);
            stringWriter.WriteLine("}");

            stringWriter.WriteIndentation(1);
            stringWriter.WriteLine("}");

            stringWriter.WriteIndentation(1);
            stringWriter.Write("private System.Collections.Immutable.ImmutableList<");
            WriteEventType(stringWriter, eventType);
            stringWriter.Write("> ");
            stringWriter.Write(internalName);
            stringWriter.WriteLine(" = [];");
            stringWriter.WriteLine();
        }
    }

    private static void WriteEventType(StringWriter stringWriter, INamedTypeSymbol eventType)
    {
        stringWriter.Write(eventType.ContainingNamespace.ToDisplayString());
        stringWriter.Write(".");
        stringWriter.Write(eventType.Name);
        stringWriter.Write("<");

        var typeArguments = eventType.TypeArguments;
        var max = typeArguments.Length - 1;
        for (var i = 0; i < max; i++)
        {
            var typeArgument = typeArguments[i];
            stringWriter.Write(typeArgument.ContainingNamespace.ToDisplayString());
            stringWriter.Write(".");
            stringWriter.Write(typeArgument.Name);

            stringWriter.Write(", ");
        }

        var lastTypeArgument = typeArguments[max];
        stringWriter.Write(lastTypeArgument.ContainingNamespace.ToDisplayString());
        stringWriter.Write(".");
        stringWriter.Write(lastTypeArgument.Name);

        stringWriter.Write(">");
    }

    private static IEventSymbol[] GetEvents(INamedTypeSymbol typeSymbol)
    {
        return [.. typeSymbol.GetMembers().OfType<IEventSymbol>()];
    }

    private static Span<char> ToInternalName(string name)
    {
        Span<char> copy = new char[name.Length + 1];
        copy[0] = '_';
        name.AsSpan(1).CopyTo(copy[2..]);
        copy[1] = char.ToLowerInvariant(name[0]);
        return copy;
    }
}
