using System.CodeDom.Compiler;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

using Shared;

namespace ShardedGatewayClientEventsGenerator;

[Generator(LanguageNames.CSharp)]
public class ShardedGatewayClientEventsGenerator : IIncrementalGenerator
{
    private const string Namespace = "NetCord.Gateway";
    private const string ShardedGatewayClientName = "ShardedGatewayClient";
    private const string GatewayClientName = "GatewayClient";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var typeSymbols = context.SyntaxProvider
            .CreateSyntaxProvider((node, cancellationToken) => node is ClassDeclarationSyntax { Identifier.Text: GatewayClientName },
                                  (context, cancellationToken) => (INamedTypeSymbol)context.SemanticModel.GetDeclaredSymbol(context.Node)!);

        context.RegisterSourceOutput(typeSymbols, (context, source) => context.AddSource("ShardedGatewayClient.g.cs", SourceText.From(GenerateEvents(source), Encoding.UTF8)));
    }

    private string GenerateEvents(INamedTypeSymbol typeSymbol)
    {
        StringWriter stringWriter = new();
        IndentedTextWriter writer = new(stringWriter);

        writer.WriteAutoGeneratedComment();
        writer.WriteLine();

        writer.WriteNullableDirective();
        writer.WriteLine();

        writer.Write("namespace ");
        writer.Write(Namespace);
        writer.WriteLine(";");
        writer.WriteLine();

        writer.Write("partial class ");
        writer.WriteLine(ShardedGatewayClientName);
        writer.WriteLine("{");
        writer.Indent++;

        var events = GetEvents(typeSymbol);

        WriteEvents(writer, events);

        WriteHookHandlersMethod(writer, events);

        writer.Indent--;
        writer.WriteLine("}");

        return stringWriter.ToString();
    }

    private void WriteEvents(IndentedTextWriter writer, IEventSymbol[] events)
    {
        foreach (var eventSymbol in events)
        {
            var eventType = (INamedTypeSymbol)eventSymbol.Type;

            writer.WriteInheritDoc(eventSymbol);

            writer.Write("public event ");

            WriteShardedEventType(writer, eventType);

            writer.Write("? ");
            writer.WriteLine(eventSymbol.Name);

            writer.WriteLine("{");
            writer.Indent++;

            writer.WriteLine("add");

            writer.WriteLine("{");
            writer.Indent++;

            writer.Write("AddHandler(");

            var internalName = ToInternalName(eventSymbol.Name);

            writer.Write(internalName);
            writer.Write(", ");
            writer.Write(internalName);
            writer.Write("Lock, value, (c, e) => c.");

            writer.Write(eventSymbol.Name);
            writer.WriteLine(" += e);");

            writer.Indent--;
            writer.WriteLine("}");

            writer.WriteLine("remove");

            writer.WriteLine("{");
            writer.Indent++;

            writer.Write("RemoveHandler(");
            writer.Write(internalName);
            writer.Write(", ");
            writer.Write(internalName);
            writer.Write("Lock, value, (c, e) => c.");
            writer.Write(eventSymbol.Name);
            writer.WriteLine(" -= e);");

            writer.Indent--;
            writer.WriteLine("}");

            writer.Indent--;
            writer.WriteLine("}");

            writer.Write("private System.Collections.Generic.Dictionary<");
            WriteShardedEventType(writer, eventType);
            writer.Write(", List<");
            WriteEventType(writer, eventType);
            writer.Write("[]>> ");
            writer.Write(internalName);
            writer.WriteLine(" = [];");

            writer.Write("private readonly System.Threading.Lock ");
            writer.Write(internalName);
            writer.WriteLine("Lock = new();");
            writer.WriteLine();
        }
    }

    private void WriteHookHandlersMethod(IndentedTextWriter writer, IEventSymbol[] events)
    {
        writer.Write("private void HookHandlers(");
        writer.Write(GatewayClientName);
        writer.WriteLine("[] clients)");

        writer.WriteLine("{");
        writer.Indent++;

        foreach (var eventSymbol in events)
        {
            writer.Write("HookHandlersToClients(clients, ");

            var internalName = ToInternalName(eventSymbol.Name);
            writer.Write(internalName);

            writer.Write(", (c, e) => c.");
            writer.Write(eventSymbol.Name);
            writer.WriteLine(" += e);");
        }

        writer.Indent--;
        writer.WriteLine("}");
    }

    private static void WriteShardedEventType(IndentedTextWriter writer, INamedTypeSymbol eventType)
    {
        writer.Write(eventType.ContainingNamespace.ToDisplayString());
        writer.Write(".");
        writer.Write(eventType.Name);
        writer.Write("<");
        writer.Write(GatewayClientName);

        var typeArguments = eventType.TypeArguments;
        int length = typeArguments.Length;
        for (int i = 0; i < length; i++)
        {
            writer.Write(", ");

            var typeArgument = typeArguments[i];
            writer.Write(typeArgument.ContainingNamespace.ToDisplayString());
            writer.Write(".");
            writer.Write(typeArgument.Name);
        }
        writer.Write(">");
    }

    private static void WriteEventType(IndentedTextWriter writer, INamedTypeSymbol eventType)
    {
        writer.Write(eventType.ContainingNamespace.ToDisplayString());
        writer.Write(".");
        writer.Write(eventType.Name);
        writer.Write("<");

        var typeArguments = eventType.TypeArguments;
        int length = typeArguments.Length;

        int i = 0;
        while (true)
        {
            var typeArgument = typeArguments[i];
            writer.Write(typeArgument.ContainingNamespace.ToDisplayString());
            writer.Write(".");
            writer.Write(typeArgument.Name);

            if (++i >= length)
                break;

            writer.Write(", ");
        }

        writer.Write(">");
    }

    private static IEventSymbol[] GetEvents(INamedTypeSymbol typeSymbol)
    {
        return
        [
            .. typeSymbol.BaseType!.GetMembers().OfType<IEventSymbol>(),
            .. typeSymbol.GetMembers().OfType<IEventSymbol>()
        ];
    }

    private static Span<char> ToInternalName(string name)
    {
        Span<char> copy = new char[name.Length + 1];
        copy[0] = '_';
        name.AsSpan(1).CopyTo(copy[2..]);
        copy[1] = char.ToLowerInvariant(name[0]);
        return copy;
    }
}
