using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

using Shared;

namespace ShardedGatewayClientEventsGenerator;

[Generator(LanguageNames.CSharp)]
public class ShardedGatewayClientEventsGenerator : IIncrementalGenerator
{
    private const string Namespace = "NetCord.Gateway";
    private const string ShardedGatewayClientName = "ShardedGatewayClient";
    private const string GatewayClientName = "GatewayClient";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var typeSymbols = context.SyntaxProvider
            .CreateSyntaxProvider((node, cancellationToken) => node is ClassDeclarationSyntax { Identifier.Text: GatewayClientName },
                                  (context, cancellationToken) => (INamedTypeSymbol)context.SemanticModel.GetDeclaredSymbol(context.Node)!);

        context.RegisterSourceOutput(typeSymbols, (context, source) => context.AddSource("ShardedGatewayClient.g.cs", SourceText.From(GenerateEvents(source), Encoding.UTF8)));
    }

    private string GenerateEvents(INamedTypeSymbol typeSymbol)
    {
        StringWriter stringWriter = new();
        stringWriter.WriteAutoGeneratedComment();
        stringWriter.WriteLine();

        stringWriter.WriteNullableDirective();
        stringWriter.WriteLine();

        stringWriter.Write("namespace ");
        stringWriter.Write(Namespace);
        stringWriter.WriteLine(";");
        stringWriter.WriteLine();

        stringWriter.Write("partial class ");
        stringWriter.WriteLine(ShardedGatewayClientName);
        stringWriter.WriteLine("{");

        var events = GetEvents(typeSymbol);

        WriteEvents(stringWriter, events);

        WriteHookEventsMethod(stringWriter, events);

        stringWriter.WriteLine("}");

        return stringWriter.ToString();
    }

    private void WriteEvents(StringWriter stringWriter, IEventSymbol[] events)
    {
        foreach (var eventSymbol in events)
        {
            var eventType = (INamedTypeSymbol)eventSymbol.Type;
            var hasArgs = eventType.Arity is 2;

            stringWriter.WriteXmlComment(eventSymbol, 1);

            stringWriter.WriteIndentation(1);
            stringWriter.Write("public event ");

            WriteEventType(stringWriter, eventType);

            stringWriter.Write("? ");
            stringWriter.WriteLine(eventSymbol.Name);

            stringWriter.WriteIndentation(1);
            stringWriter.WriteLine("{");

            stringWriter.WriteIndentation(2);
            stringWriter.WriteLine("add");

            stringWriter.WriteIndentation(2);
            stringWriter.WriteLine("{");

            stringWriter.WriteIndentation(3);
            stringWriter.Write("HookEvent(");

            var internalName = ToInternalName(eventSymbol.Name);

            stringWriter.Write(internalName);
            stringWriter.Write("Lock, value, ref ");
            stringWriter.Write(internalName);
            stringWriter.Write(", client => ");

            if (hasArgs)
                stringWriter.Write("a => ");
            else
                stringWriter.Write("() => ");

            stringWriter.Write(internalName);

            if (hasArgs)
                stringWriter.Write("!(client, a), (c, e) => c.");
            else
                stringWriter.Write("!(client), (c, e) => c.");

            stringWriter.Write(eventSymbol.Name);
            stringWriter.WriteLine(" += e);");

            stringWriter.WriteIndentation(2);
            stringWriter.WriteLine("}");

            stringWriter.WriteIndentation(2);
            stringWriter.WriteLine("remove");

            stringWriter.WriteIndentation(2);
            stringWriter.WriteLine("{");

            stringWriter.WriteIndentation(3);
            stringWriter.Write("UnhookEvent(");
            stringWriter.Write(internalName);
            stringWriter.Write("Lock, value, ref ");
            stringWriter.Write(internalName);
            stringWriter.Write(", (c, e) => c.");
            stringWriter.Write(eventSymbol.Name);
            stringWriter.WriteLine(" -= e);");

            stringWriter.WriteIndentation(2);
            stringWriter.WriteLine("}");

            stringWriter.WriteIndentation(1);
            stringWriter.WriteLine("}");

            stringWriter.WriteIndentation(1);
            stringWriter.Write("private ");

            WriteEventType(stringWriter, eventType);

            stringWriter.Write("? ");
            stringWriter.Write(internalName);
            stringWriter.WriteLine(";");

            stringWriter.WriteIndentation(1);
            stringWriter.Write("private readonly System.Threading.Lock ");
            stringWriter.Write(internalName);
            stringWriter.WriteLine("Lock = new();");
            stringWriter.WriteLine();
        }
    }

    private void WriteHookEventsMethod(StringWriter stringWriter, IEventSymbol[] events)
    {
        stringWriter.WriteIndentation(1);
        stringWriter.Write("private void HookEvents(");
        stringWriter.Write(GatewayClientName);
        stringWriter.WriteLine(" client)");

        stringWriter.WriteIndentation(1);
        stringWriter.WriteLine("{");

        foreach (var eventSymbol in events)
        {
            var eventType = (INamedTypeSymbol)eventSymbol.Type;
            var hasArgs = eventType.Arity is 2;

            stringWriter.WriteIndentation(2);

            stringWriter.Write("HookEvent(client, ");

            var internalName = ToInternalName(eventSymbol.Name);

            stringWriter.Write(internalName);
            stringWriter.Write("Lock, ref ");
            stringWriter.Write(internalName);

            if (hasArgs)
                stringWriter.Write(", a => ");
            else
                stringWriter.Write(", () => ");

            stringWriter.Write(internalName);

            if (hasArgs)
                stringWriter.Write("!(client, a), (c, e) => c.");
            else
                stringWriter.Write("!(client), (c, e) => c.");

            stringWriter.Write(eventSymbol.Name);
            stringWriter.WriteLine(" += e);");
        }

        stringWriter.WriteIndentation(1);
        stringWriter.WriteLine("}");
    }

    private static void WriteEventType(StringWriter stringWriter, INamedTypeSymbol eventType)
    {
        stringWriter.Write(eventType.ContainingNamespace.ToDisplayString());
        stringWriter.Write(".");
        stringWriter.Write(eventType.Name);
        stringWriter.Write("<");
        stringWriter.Write(GatewayClientName);

        var typeArguments = eventType.TypeArguments;
        int length = typeArguments.Length;
        for (int i = 0; i < length; i++)
        {
            stringWriter.Write(", ");

            var typeArgument = typeArguments[i];
            stringWriter.Write(typeArgument.ContainingNamespace.ToDisplayString());
            stringWriter.Write(".");
            stringWriter.Write(typeArgument.Name);
        }
        stringWriter.Write(">");
    }

    private static IEventSymbol[] GetEvents(INamedTypeSymbol typeSymbol)
    {
        return
        [
            .. typeSymbol.BaseType!.GetMembers().OfType<IEventSymbol>(),
            .. typeSymbol.GetMembers().OfType<IEventSymbol>()
        ];
    }

    private static Span<char> ToInternalName(string name)
    {
        Span<char> copy = new char[name.Length + 1];
        copy[0] = '_';
        name.AsSpan(1).CopyTo(copy[2..]);
        copy[1] = char.ToLowerInvariant(name[0]);
        return copy;
    }
}
