using System.Collections.Immutable;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

using Shared;

namespace HostingGatewayEventsGenerator;

[Generator(LanguageNames.CSharp)]
public class HostingGatewayEventsGenerator : IIncrementalGenerator
{
    private const string Namespace = "NetCord.Hosting.Gateway";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var typeSymbols = context.CompilationProvider
            .Select<Compilation, ImmutableArray<INamedTypeSymbol>>((compilation, cancellationToken) =>
            {
                return [compilation.GetTypeByMetadataName("NetCord.Gateway.WebSocketClient")!, compilation.GetTypeByMetadataName("NetCord.Gateway.GatewayClient")!];
            })
            .Select((types, cancellationToken) => GetEvents(types)).WithComparer(SymbolArrayEqualityComparer.Default);

        context.RegisterSourceOutput(typeSymbols, (context, source) =>
        {
            context.AddSource("GatewayEvent.g.cs", SourceText.From(GenerateEvents(source), Encoding.UTF8));

            context.AddSource("GatewayHandlerInterfaces.g.cs", SourceText.From(GenerateHandlerInterfaces(source), Encoding.UTF8));

            context.AddSource("GatewayClientHostedService.g.cs", SourceText.From(GenerateHandlerRegistrationMethods(source), Encoding.UTF8));

            context.AddSource("ShardedGatewayClientHostedService.g.cs", SourceText.From(GenerateShardedHandlerRegistrationMethods(source), Encoding.UTF8));
        });
    }

    private static void Setup(StringWriter stringWriter)
    {
        stringWriter.WriteAutoGeneratedComment();
        stringWriter.WriteLine();

        stringWriter.WriteNullableDirective();
        stringWriter.WriteLine();

        stringWriter.Write("namespace ");
        stringWriter.Write(Namespace);
        stringWriter.WriteLine(";");
    }

    private string GenerateEvents(IEventSymbol[] events)
    {
        StringWriter stringWriter = new();
        Setup(stringWriter);

        WriteEventsEnum(stringWriter, events);

        stringWriter.WriteLine();

        WriteEvents(stringWriter, events);

        return stringWriter.ToString();
    }

    private void WriteEventsEnum(StringWriter stringWriter, IEventSymbol[] events)
    {
        stringWriter.WriteLine();

        stringWriter.WriteLine("internal enum GatewayEventId : byte");

        stringWriter.WriteLine("{");

        foreach (var eventSymbol in events)
        {
            stringWriter.WriteIndentation(1);
            stringWriter.Write(eventSymbol.Name);
            stringWriter.WriteLine(",");
        }

        stringWriter.WriteLine("}");
    }

    private void WriteEvents(StringWriter stringWriter, IEventSymbol[] events)
    {
        stringWriter.WriteLine();

        stringWriter.WriteLine("partial class GatewayEvent");
        stringWriter.Write("{");

        foreach (var eventSymbol in events)
        {
            stringWriter.WriteLine();

            stringWriter.WriteInheritDoc(eventSymbol, 1);

            stringWriter.WriteIndentation(1);
            stringWriter.Write("public static global::");
            stringWriter.Write(Namespace);
            stringWriter.Write(".GatewayEvent");

            var eventType = (INamedTypeSymbol)eventSymbol.Type;
            if (eventType.Arity is 2)
            {
                stringWriter.Write("<");
                stringWriter.Write(eventType.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
                stringWriter.Write(">");
            }

            stringWriter.Write(" ");
            stringWriter.Write(eventSymbol.Name);
            stringWriter.Write(" => new(global::NetCord.Hosting.Gateway.GatewayEventId.");
            stringWriter.Write(eventSymbol.Name);
            stringWriter.WriteLine(");");
        }

        stringWriter.WriteLine("}");
    }

    private string GenerateHandlerInterfaces(IEventSymbol[] events)
    {
        StringWriter stringWriter = new();
        Setup(stringWriter);

        WriteGatewayHandlerInterfaces(stringWriter, events);

        return stringWriter.ToString();
    }

    private void WriteGatewayHandlerInterfaces(StringWriter stringWriter, IEventSymbol[] events)
    {
        foreach (var eventSymbol in events)
        {
            stringWriter.WriteLine();

            stringWriter.WriteInheritDoc(eventSymbol, 0);

            stringWriter.Write("public interface I");
            stringWriter.Write(eventSymbol.Name);
            stringWriter.WriteLine("GatewayHandler : global::NetCord.Hosting.Gateway.IGatewayHandler");

            stringWriter.WriteLine("{");

            var eventType = (INamedTypeSymbol)eventSymbol.Type;
            var hasArg = eventType.Arity is 2;

            WriteHandleAsyncXmlDoc(stringWriter, false, hasArg);

            stringWriter.WriteIndentation(1);
            stringWriter.Write("public global::System.Threading.Tasks.ValueTask HandleAsync(");

            if (hasArg)
            {
                stringWriter.Write(eventType.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
                stringWriter.Write(" arg");
            }

            stringWriter.WriteLine(");");

            stringWriter.WriteLine("}");

            stringWriter.WriteLine();

            stringWriter.WriteInheritDoc(eventSymbol, 0);

            stringWriter.Write("public interface I");
            stringWriter.Write(eventSymbol.Name);
            stringWriter.WriteLine("ShardedGatewayHandler : global::NetCord.Hosting.Gateway.IShardedGatewayHandler");

            stringWriter.WriteLine("{");

            WriteHandleAsyncXmlDoc(stringWriter, true, hasArg);

            stringWriter.WriteIndentation(1);
            stringWriter.Write("public global::System.Threading.Tasks.ValueTask HandleAsync(global::NetCord.Gateway.GatewayClient client");

            if (hasArg)
            {
                stringWriter.Write(", ");
                stringWriter.Write(eventType.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
                stringWriter.Write(" arg");
            }

            stringWriter.WriteLine(");");

            stringWriter.WriteLine("}");
        }
    }

    private void WriteHandleAsyncXmlDoc(StringWriter stringWriter, bool hasClient, bool hasArg)
    {
        stringWriter.WriteIndentation(1);
        stringWriter.WriteLine("/// <summary>");

        stringWriter.WriteIndentation(1);
        stringWriter.WriteLine("/// Handles the gateway event.");

        stringWriter.WriteIndentation(1);
        stringWriter.WriteLine("/// </summary>");

        if (hasClient)
        {
            stringWriter.WriteIndentation(1);
            stringWriter.WriteLine("/// <param name=\"client\">The gateway client that represents the shard that received the event.</param>");
        }

        if (hasArg)
        {
            stringWriter.WriteIndentation(1);
            stringWriter.WriteLine("/// <param name=\"arg\">The event argument.</param>");
        }
    }

    private string GenerateHandlerRegistrationMethods(IEventSymbol[] events)
    {
        StringWriter stringWriter = new();
        Setup(stringWriter);

        WriteRegisterHandlerMethods(stringWriter, events);

        return stringWriter.ToString();
    }

    private string GenerateShardedHandlerRegistrationMethods(IEventSymbol[] events)
    {
        StringWriter stringWriter = new();
        Setup(stringWriter);

        WriteRegisterShardedHandlerMethods(stringWriter, events);

        return stringWriter.ToString();
    }

    private void WriteRegisterHandlerMethods(StringWriter stringWriter, IEventSymbol[] events)
    {
        stringWriter.WriteLine();

        stringWriter.WriteLine("partial class GatewayClientHostedService");

        stringWriter.Write("{");

        WriteRegisterDelegateHandlerMethod(stringWriter, events);

        WriteRegisterClassHandlerMethod(stringWriter, events);

        stringWriter.WriteLine("}");
    }

    private void WriteRegisterShardedHandlerMethods(StringWriter stringWriter, IEventSymbol[] events)
    {
        stringWriter.WriteLine();

        stringWriter.WriteLine("partial class ShardedGatewayClientHostedService");

        stringWriter.Write("{");

        WriteRegisterDelegateShardedHandlerMethod(stringWriter, events);

        WriteRegisterClassShardedHandlerMethod(stringWriter, events);

        stringWriter.WriteLine("}");
    }

    private void WriteRegisterDelegateHandlerMethod(StringWriter stringWriter, IEventSymbol[] events)
    {
        stringWriter.WriteLine();

        stringWriter.WriteIndentation(1);
        stringWriter.WriteLine("private static void RegisterDelegateHandler(IServiceProvider services, global::NetCord.Gateway.GatewayClient client, global::NetCord.Hosting.Gateway.DelegateGatewayHandlerMetadata handlerMetadata)");

        stringWriter.WriteIndentation(1);
        stringWriter.WriteLine("{");

        stringWriter.WriteIndentation(2);
        stringWriter.WriteLine("var isSingleton = handlerMetadata.IsSingleton;");

        stringWriter.WriteIndentation(2);
        stringWriter.WriteLine("switch (handlerMetadata.EventId)");

        stringWriter.WriteIndentation(2);
        stringWriter.WriteLine("{");

        int eventsLength = events.Length;
        for (int i = 0; i < eventsLength; i++)
        {
            var eventSymbol = events[i];

            stringWriter.WriteIndentation(3);
            stringWriter.Write("case global::NetCord.Hosting.Gateway.GatewayEventId.");
            stringWriter.Write(eventSymbol.Name);
            stringWriter.WriteLine(":");

            stringWriter.WriteIndentation(4);
            stringWriter.Write("var typedHandler");
            stringWriter.Write(i);
            stringWriter.Write(" = (global::System.Func<");

            var eventType = (INamedTypeSymbol)eventSymbol.Type;
            if (eventType.Arity is not 1)
            {
                stringWriter.Write(eventType.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
                stringWriter.Write(", ");
            }

            stringWriter.WriteLine("global::System.IServiceProvider, global::System.Threading.Tasks.ValueTask>)handlerMetadata.Handler;");

            stringWriter.WriteIndentation(4);
            stringWriter.Write("client.");
            stringWriter.Write(eventSymbol.Name);
            stringWriter.WriteLine(" += isSingleton");

            stringWriter.WriteIndentation(5);
            stringWriter.Write("? (");

            if (eventType.Arity is not 1)
                stringWriter.Write("arg");

            stringWriter.Write(") => typedHandler");
            stringWriter.Write(i);
            stringWriter.Write("(");

            if (eventType.Arity is not 1)
                stringWriter.Write("arg, ");

            stringWriter.WriteLine("services)");

            stringWriter.WriteIndentation(5);
            stringWriter.Write(": async (");

            if (eventType.Arity is not 1)
                stringWriter.Write("arg");

            stringWriter.WriteLine(") =>");

            stringWriter.WriteIndentation(5);
            stringWriter.WriteLine("{");

            stringWriter.WriteIndentation(6);
            stringWriter.WriteLine("await using var scope = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.CreateAsyncScope(services);");

            stringWriter.WriteIndentation(6);
            stringWriter.Write("await typedHandler");
            stringWriter.Write(i);
            stringWriter.Write("(");

            if (eventType.Arity is not 1)
                stringWriter.Write("arg, ");

            stringWriter.WriteLine("scope.ServiceProvider);");

            stringWriter.WriteIndentation(5);
            stringWriter.WriteLine("};");

            stringWriter.WriteIndentation(4);
            stringWriter.WriteLine("break;");
        }

        stringWriter.WriteIndentation(2);
        stringWriter.WriteLine("}");

        stringWriter.WriteIndentation(1);
        stringWriter.WriteLine("}");
    }

    private void WriteRegisterClassHandlerMethod(StringWriter stringWriter, IEventSymbol[] events)
    {
        stringWriter.WriteLine();

        stringWriter.WriteIndentation(1);
        stringWriter.WriteLine("private static void RegisterClassHandler(global::System.IServiceProvider services, global::NetCord.Gateway.GatewayClient client, global::NetCord.Hosting.Gateway.ClassGatewayHandlerMetadata handlerMetadata)");

        stringWriter.WriteIndentation(1);
        stringWriter.WriteLine("{");

        stringWriter.WriteIndentation(2);
        stringWriter.WriteLine("var handlerType = handlerMetadata.HandlerType;");

        stringWriter.WriteIndentation(2);
        stringWriter.WriteLine("var isSingleton = handlerMetadata.IsSingleton;");

        int eventsLength = events.Length;

        for (int i = 0; i < eventsLength; i++)
        {
            var eventSymbol = events[i];

            var eventType = (INamedTypeSymbol)eventSymbol.Type;

            stringWriter.WriteLine();

            stringWriter.WriteIndentation(2);
            stringWriter.Write("if (typeof(global::NetCord.Hosting.Gateway.I");
            stringWriter.Write(eventSymbol.Name);
            stringWriter.WriteLine("GatewayHandler).IsAssignableFrom(handlerType))");

            stringWriter.WriteIndentation(2);
            stringWriter.WriteLine("{");

            stringWriter.WriteIndentation(3);
            stringWriter.Write("client.");
            stringWriter.Write(eventSymbol.Name);
            stringWriter.WriteLine(" += isSingleton");

            stringWriter.WriteIndentation(4);
            stringWriter.Write("? ((global::NetCord.Hosting.Gateway.I");
            stringWriter.Write(eventSymbol.Name);
            stringWriter.WriteLine("GatewayHandler)global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(services, handlerMetadata.HandlerType)).HandleAsync");

            stringWriter.WriteIndentation(4);
            stringWriter.WriteLine(eventType.Arity is 1 ? ": async () =>" : ": async (arg) =>");

            stringWriter.WriteIndentation(4);
            stringWriter.WriteLine("{");

            stringWriter.WriteIndentation(5);
            stringWriter.WriteLine("await using var scope = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.CreateAsyncScope(services);");

            stringWriter.WriteIndentation(5);
            stringWriter.Write("await ((global::NetCord.Hosting.Gateway.I");
            stringWriter.Write(eventSymbol.Name);
            stringWriter.Write("GatewayHandler)global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(scope.ServiceProvider, handlerMetadata.HandlerType)).HandleAsync(");

            if (eventType.Arity is not 1)
                stringWriter.Write("arg");

            stringWriter.WriteLine(");");

            stringWriter.WriteIndentation(4);
            stringWriter.WriteLine("};");

            stringWriter.WriteIndentation(2);
            stringWriter.WriteLine("}");
        }

        stringWriter.WriteIndentation(1);
        stringWriter.WriteLine("}");
    }

    private void WriteRegisterDelegateShardedHandlerMethod(StringWriter stringWriter, IEventSymbol[] events)
    {
        stringWriter.WriteLine();

        stringWriter.WriteIndentation(1);
        stringWriter.WriteLine("private static void RegisterDelegateShardedHandler(global::NetCord.Gateway.ShardedGatewayClient client, global::NetCord.Hosting.Gateway.IDelegateShardedGatewayHandlerBase handler)");

        stringWriter.WriteIndentation(1);
        stringWriter.Write("{");

        int i = 0;
        foreach (var group in events.GroupBy(e => e.Type, SymbolEqualityComparer.Default))
        {
            var eventType = (INamedTypeSymbol)group.Key!;

            stringWriter.WriteLine();

            stringWriter.WriteIndentation(2);
            stringWriter.Write("if (handler is global::NetCord.Hosting.Gateway.IDelegateShardedGatewayHandler");

            if (eventType.Arity is 2)
            {
                stringWriter.Write("<");
                stringWriter.Write(eventType.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
                stringWriter.Write(">");
            }

            stringWriter.Write(" delegateGatewayHandler");
            stringWriter.Write(i);
            stringWriter.WriteLine(")");

            stringWriter.WriteIndentation(2);
            stringWriter.WriteLine("{");

            stringWriter.WriteIndentation(3);
            stringWriter.Write("switch (delegateGatewayHandler");
            stringWriter.Write(i);
            stringWriter.WriteLine(".Name)");

            stringWriter.WriteIndentation(3);
            stringWriter.WriteLine("{");

            foreach (var eventSymbol in group)
            {
                stringWriter.WriteIndentation(4);
                stringWriter.Write("case \"");
                stringWriter.Write(eventSymbol.Name);
                stringWriter.WriteLine("\":");

                stringWriter.WriteIndentation(5);
                stringWriter.Write("client.");
                stringWriter.Write(eventSymbol.Name);
                stringWriter.Write(" += delegateGatewayHandler");
                stringWriter.Write(i);
                stringWriter.WriteLine(".HandleAsync;");

                stringWriter.WriteIndentation(5);
                stringWriter.WriteLine("break;");
            }

            stringWriter.WriteIndentation(3);
            stringWriter.WriteLine("}");

            stringWriter.WriteIndentation(3);
            stringWriter.WriteLine("return;");

            stringWriter.WriteIndentation(2);
            stringWriter.WriteLine("}");

            i++;
        }

        stringWriter.WriteIndentation(1);
        stringWriter.WriteLine("}");
    }

    private void WriteRegisterClassShardedHandlerMethod(StringWriter stringWriter, IEventSymbol[] events)
    {
        stringWriter.WriteLine();

        stringWriter.WriteIndentation(1);
        stringWriter.WriteLine("private static void RegisterClassShardedHandler(global::NetCord.Gateway.ShardedGatewayClient client, global::NetCord.Hosting.Gateway.IShardedGatewayHandler handler)");

        stringWriter.WriteIndentation(1);
        stringWriter.Write("{");

        int eventsLength = events.Length;

        for (int i = 0; i < eventsLength; i++)
        {
            var eventSymbol = events[i];

            stringWriter.WriteLine();

            stringWriter.WriteIndentation(2);
            stringWriter.Write("if (handler is global::NetCord.Hosting.Gateway.I");
            stringWriter.Write(eventSymbol.Name);
            stringWriter.Write("ShardedGatewayHandler gatewayHandler");
            stringWriter.Write(i);
            stringWriter.WriteLine(")");

            stringWriter.WriteIndentation(3);
            stringWriter.Write("client.");
            stringWriter.Write(eventSymbol.Name);
            stringWriter.Write(" += gatewayHandler");
            stringWriter.Write(i);
            stringWriter.WriteLine(".HandleAsync;");
        }

        stringWriter.WriteIndentation(1);
        stringWriter.WriteLine("}");
    }

    private static IEventSymbol[] GetEvents(ImmutableArray<INamedTypeSymbol> typeSymbols)
    {
        return [.. typeSymbols.SelectMany(symbol => symbol.GetMembers()).OfType<IEventSymbol>()];
    }
}
