using System.Collections.Immutable;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

using Shared;

namespace HostingGatewayEventsGenerator;

[Generator(LanguageNames.CSharp)]
public class HostingGatewayEventsGenerator : IIncrementalGenerator
{
    private const string Namespace = "NetCord.Hosting.Gateway";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var typeSymbols = context.CompilationProvider
            .Select<Compilation, ImmutableArray<INamedTypeSymbol>>((compilation, cancellationToken) =>
            {
                return [compilation.GetTypeByMetadataName("NetCord.Gateway.WebSocketClient")!, compilation.GetTypeByMetadataName("NetCord.Gateway.GatewayClient")!];
            })
            .Select((types, cancellationToken) => GetEvents(types)).WithComparer(SymbolArrayEqualityComparer.Default);

        context.RegisterSourceOutput(typeSymbols, (context, source) =>
        {
            context.AddSource("GatewayEvent.g.cs", SourceText.From(GenerateEvents(source), Encoding.UTF8));

            context.AddSource("GatewayHandlerInterfaces.g.cs", SourceText.From(GenerateHandlerInterfaces(source), Encoding.UTF8));

            context.AddSource("GatewayHandlerHostExtensions.g.cs", SourceText.From(GenerateHandlerRegistrationMethods(source), Encoding.UTF8));
        });
    }

    private static void Setup(StringWriter stringWriter)
    {
        stringWriter.WriteAutoGeneratedComment();
        stringWriter.WriteLine();

        stringWriter.WriteNullableDirective();
        stringWriter.WriteLine();

        stringWriter.Write("namespace ");
        stringWriter.Write(Namespace);
        stringWriter.WriteLine(";");
    }

    private string GenerateEvents(IEventSymbol[] events)
    {
        StringWriter stringWriter = new();
        Setup(stringWriter);

        WriteEvents(stringWriter, events);

        return stringWriter.ToString();
    }

    private void WriteEvents(StringWriter stringWriter, IEventSymbol[] events)
    {
        stringWriter.WriteLine();

        stringWriter.WriteLine("partial class GatewayEvent");
        stringWriter.Write("{");

        foreach (var eventSymbol in events)
        {
            stringWriter.WriteLine();

            stringWriter.WriteInheritDoc(eventSymbol, 1);

            stringWriter.WriteIndentation(1);
            stringWriter.Write("public static global::");
            stringWriter.Write(Namespace);
            stringWriter.Write(".GatewayEvent");

            var eventType = (INamedTypeSymbol)eventSymbol.Type;
            if (eventType.Arity is 2)
            {
                stringWriter.Write("<");
                stringWriter.Write(eventType.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
                stringWriter.Write(">");
            }

            stringWriter.Write(" ");
            stringWriter.Write(eventSymbol.Name);
            stringWriter.Write(" => new(\"");
            stringWriter.Write(eventSymbol.Name);
            stringWriter.WriteLine("\");");
        }

        stringWriter.WriteLine("}");
    }

    private string GenerateHandlerInterfaces(IEventSymbol[] events)
    {
        StringWriter stringWriter = new();
        Setup(stringWriter);

        WriteGatewayHandlerInterfaces(stringWriter, events);

        return stringWriter.ToString();
    }

    private void WriteGatewayHandlerInterfaces(StringWriter stringWriter, IEventSymbol[] events)
    {
        foreach (var eventSymbol in events)
        {
            stringWriter.WriteLine();

            stringWriter.WriteInheritDoc(eventSymbol, 0);

            stringWriter.Write("public interface I");
            stringWriter.Write(eventSymbol.Name);
            stringWriter.WriteLine("GatewayHandler : global::NetCord.Hosting.Gateway.IGatewayHandler");

            stringWriter.WriteLine("{");

            stringWriter.WriteIndentation(1);
            stringWriter.Write("public global::System.Threading.Tasks.ValueTask HandleAsync(");

            var eventType = (INamedTypeSymbol)eventSymbol.Type;
            if (eventType.Arity is 2)
            {
                stringWriter.Write(eventType.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
                stringWriter.Write(" arg");
            }

            stringWriter.WriteLine(");");

            stringWriter.WriteLine("}");

            stringWriter.WriteLine();

            stringWriter.WriteInheritDoc(eventSymbol, 0);

            stringWriter.Write("public interface I");
            stringWriter.Write(eventSymbol.Name);
            stringWriter.WriteLine("ShardedGatewayHandler : global::NetCord.Hosting.Gateway.IShardedGatewayHandler");

            stringWriter.WriteLine("{");

            stringWriter.WriteIndentation(1);
            stringWriter.Write("public global::System.Threading.Tasks.ValueTask HandleAsync(global::NetCord.Gateway.GatewayClient client");

            if (eventType.Arity is 2)
            {
                stringWriter.Write(", ");
                stringWriter.Write(eventType.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
                stringWriter.Write(" arg");
            }

            stringWriter.WriteLine(");");

            stringWriter.WriteLine("}");
        }
    }

    private string GenerateHandlerRegistrationMethods(IEventSymbol[] events)
    {
        StringWriter stringWriter = new();
        Setup(stringWriter);

        WriteRegisterHandlerMethods(stringWriter, events);

        return stringWriter.ToString();
    }

    private void WriteRegisterHandlerMethods(StringWriter stringWriter, IEventSymbol[] events)
    {
        stringWriter.WriteLine();

        stringWriter.WriteLine("partial class GatewayHandlerHostExtensions");

        stringWriter.Write("{");

        WriteRegisterDelegateHandlerMethod(stringWriter, events);

        WriteRegisterClassHandlerMethod(stringWriter, events);

        WriteRegisterDelegateShardedHandlerMethod(stringWriter, events);

        WriteRegisterClassShardedHandlerMethod(stringWriter, events);

        stringWriter.WriteLine("}");
    }

    private void WriteRegisterDelegateHandlerMethod(StringWriter stringWriter, IEventSymbol[] events)
    {
        stringWriter.WriteLine();

        stringWriter.WriteIndentation(1);
        stringWriter.WriteLine("private static void RegisterDelegateHandler(global::NetCord.Gateway.GatewayClient client, global::NetCord.Hosting.Gateway.IDelegateGatewayHandlerBase handler)");

        stringWriter.WriteIndentation(1);
        stringWriter.Write("{");

        int i = 0;
        foreach (var group in events.GroupBy(e => e.Type, SymbolEqualityComparer.Default))
        {
            var eventType = (INamedTypeSymbol)group.Key!;

            stringWriter.WriteLine();

            stringWriter.WriteIndentation(2);
            stringWriter.Write("if (handler is global::NetCord.Hosting.Gateway.IDelegateGatewayHandler");

            if (eventType.Arity is 2)
            {
                stringWriter.Write("<");
                stringWriter.Write(eventType.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
                stringWriter.Write(">");
            }

            stringWriter.Write(" delegateGatewayHandler");
            stringWriter.Write(i);
            stringWriter.WriteLine(")");

            stringWriter.WriteIndentation(2);
            stringWriter.WriteLine("{");

            stringWriter.WriteIndentation(3);
            stringWriter.Write("switch (delegateGatewayHandler");
            stringWriter.Write(i);
            stringWriter.WriteLine(".Name)");

            stringWriter.WriteIndentation(3);
            stringWriter.WriteLine("{");

            foreach (var eventSymbol in group)
            {
                stringWriter.WriteIndentation(4);
                stringWriter.Write("case \"");
                stringWriter.Write(eventSymbol.Name);
                stringWriter.WriteLine("\":");

                stringWriter.WriteIndentation(5);
                stringWriter.Write("client.");
                stringWriter.Write(eventSymbol.Name);
                stringWriter.Write(" += delegateGatewayHandler");
                stringWriter.Write(i);
                stringWriter.WriteLine(".HandleAsync;");

                stringWriter.WriteIndentation(5);
                stringWriter.WriteLine("break;");
            }

            stringWriter.WriteIndentation(3);
            stringWriter.WriteLine("}");

            stringWriter.WriteIndentation(3);
            stringWriter.WriteLine("return;");

            stringWriter.WriteIndentation(2);
            stringWriter.WriteLine("}");

            i++;
        }

        stringWriter.WriteIndentation(1);
        stringWriter.WriteLine("}");
    }

    private void WriteRegisterClassHandlerMethod(StringWriter stringWriter, IEventSymbol[] events)
    {
        stringWriter.WriteLine();

        stringWriter.WriteIndentation(1);
        stringWriter.WriteLine("private static void RegisterClassHandler(global::NetCord.Gateway.GatewayClient client, global::NetCord.Hosting.Gateway.IGatewayHandler handler)");

        stringWriter.WriteIndentation(1);
        stringWriter.Write("{");

        int eventsLength = events.Length;

        for (int i = 0; i < eventsLength; i++)
        {
            var eventSymbol = events[i];

            stringWriter.WriteLine();

            stringWriter.WriteIndentation(2);
            stringWriter.Write("if (handler is global::NetCord.Hosting.Gateway.I");
            stringWriter.Write(eventSymbol.Name);
            stringWriter.Write("GatewayHandler gatewayHandler");
            stringWriter.Write(i);
            stringWriter.WriteLine(")");

            stringWriter.WriteIndentation(3);
            stringWriter.Write("client.");
            stringWriter.Write(eventSymbol.Name);
            stringWriter.Write(" += gatewayHandler");
            stringWriter.Write(i);
            stringWriter.WriteLine(".HandleAsync;");
        }

        stringWriter.WriteIndentation(1);
        stringWriter.WriteLine("}");
    }

    private void WriteRegisterDelegateShardedHandlerMethod(StringWriter stringWriter, IEventSymbol[] events)
    {
        stringWriter.WriteLine();

        stringWriter.WriteIndentation(1);
        stringWriter.WriteLine("private static void RegisterDelegateShardedHandler(global::NetCord.Gateway.ShardedGatewayClient client, global::NetCord.Hosting.Gateway.IDelegateShardedGatewayHandlerBase handler)");

        stringWriter.WriteIndentation(1);
        stringWriter.Write("{");

        int i = 0;
        foreach (var group in events.GroupBy(e => e.Type, SymbolEqualityComparer.Default))
        {
            var eventType = (INamedTypeSymbol)group.Key!;

            stringWriter.WriteLine();

            stringWriter.WriteIndentation(2);
            stringWriter.Write("if (handler is global::NetCord.Hosting.Gateway.IDelegateShardedGatewayHandler");

            if (eventType.Arity is 2)
            {
                stringWriter.Write("<");
                stringWriter.Write(eventType.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
                stringWriter.Write(">");
            }

            stringWriter.Write(" delegateGatewayHandler");
            stringWriter.Write(i);
            stringWriter.WriteLine(")");

            stringWriter.WriteIndentation(2);
            stringWriter.WriteLine("{");

            stringWriter.WriteIndentation(3);
            stringWriter.Write("switch (delegateGatewayHandler");
            stringWriter.Write(i);
            stringWriter.WriteLine(".Name)");

            stringWriter.WriteIndentation(3);
            stringWriter.WriteLine("{");

            foreach (var eventSymbol in group)
            {
                stringWriter.WriteIndentation(4);
                stringWriter.Write("case \"");
                stringWriter.Write(eventSymbol.Name);
                stringWriter.WriteLine("\":");

                stringWriter.WriteIndentation(5);
                stringWriter.Write("client.");
                stringWriter.Write(eventSymbol.Name);
                stringWriter.Write(" += delegateGatewayHandler");
                stringWriter.Write(i);
                stringWriter.WriteLine(".HandleAsync;");

                stringWriter.WriteIndentation(5);
                stringWriter.WriteLine("break;");
            }

            stringWriter.WriteIndentation(3);
            stringWriter.WriteLine("}");

            stringWriter.WriteIndentation(3);
            stringWriter.WriteLine("return;");

            stringWriter.WriteIndentation(2);
            stringWriter.WriteLine("}");

            i++;
        }

        stringWriter.WriteIndentation(1);
        stringWriter.WriteLine("}");
    }

    private void WriteRegisterClassShardedHandlerMethod(StringWriter stringWriter, IEventSymbol[] events)
    {
        stringWriter.WriteLine();

        stringWriter.WriteIndentation(1);
        stringWriter.WriteLine("private static void RegisterClassShardedHandler(global::NetCord.Gateway.ShardedGatewayClient client, global::NetCord.Hosting.Gateway.IShardedGatewayHandler handler)");

        stringWriter.WriteIndentation(1);
        stringWriter.Write("{");

        int eventsLength = events.Length;

        for (int i = 0; i < eventsLength; i++)
        {
            var eventSymbol = events[i];

            stringWriter.WriteLine();

            stringWriter.WriteIndentation(2);
            stringWriter.Write("if (handler is global::NetCord.Hosting.Gateway.I");
            stringWriter.Write(eventSymbol.Name);
            stringWriter.Write("ShardedGatewayHandler gatewayHandler");
            stringWriter.Write(i);
            stringWriter.WriteLine(")");

            stringWriter.WriteIndentation(3);
            stringWriter.Write("client.");
            stringWriter.Write(eventSymbol.Name);
            stringWriter.Write(" += gatewayHandler");
            stringWriter.Write(i);
            stringWriter.WriteLine(".HandleAsync;");
        }

        stringWriter.WriteIndentation(1);
        stringWriter.WriteLine("}");
    }

    private static IEventSymbol[] GetEvents(ImmutableArray<INamedTypeSymbol> typeSymbols)
    {
        return [.. typeSymbols.SelectMany(symbol => symbol.GetMembers()).OfType<IEventSymbol>()];
    }
}
