using System.CodeDom.Compiler;
using System.Collections.Immutable;
using System.Text;

using HandlerGenerator.Common;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

using Shared;

namespace HostingGatewayEventsGenerator;

[Generator(LanguageNames.CSharp)]
public class HostingGatewayEventsGenerator : IIncrementalGenerator
{
    private const string Namespace = "NetCord.Hosting.Gateway";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var typeSymbols = context.CompilationProvider
            .Select<Compilation, ImmutableArray<INamedTypeSymbol>>((compilation, cancellationToken) =>
            {
                return [compilation.GetTypeByMetadataName("NetCord.Gateway.WebSocketClient")!, compilation.GetTypeByMetadataName("NetCord.Gateway.GatewayClient")!];
            })
            .Select((types, cancellationToken) => GetEvents(types)).WithComparer(SymbolArrayEqualityComparer.Default);

        context.RegisterSourceOutput(typeSymbols, (context, source) =>
        {
            context.AddSource("GatewayEvent.g.cs", SourceText.From(GenerateEvents(source), Encoding.UTF8));

            context.AddSource("GatewayHandlerInterfaces.g.cs", SourceText.From(GenerateHandlerInterfaces(source), Encoding.UTF8));

            context.AddSource("GatewayClientHostedService.g.cs", SourceText.From(GenerateHandlerRegistrationMethods(source), Encoding.UTF8));

            context.AddSource("ShardedGatewayClientHostedService.g.cs", SourceText.From(GenerateShardedHandlerRegistrationMethods(source), Encoding.UTF8));
        });
    }

    private static void Setup(TextWriter writer)
    {
        writer.WriteAutoGeneratedComment();
        writer.WriteLine();

        writer.WriteNullableDirective();
        writer.WriteLine();

        writer.Write("namespace ");
        writer.Write(Namespace);
        writer.WriteLine(";");
    }

    private string GenerateEvents(IEventSymbol[] events)
    {
        StringWriter writer = new();
        Setup(writer);

        WriteEventsEnum(writer, events);

        WriteEvents(writer, events);

        return writer.ToString();
    }

    private void WriteEventsEnum(StringWriter writer, IEventSymbol[] events)
    {
        writer.WriteLine();

        writer.WriteLine("internal enum GatewayEventId : byte");

        writer.WriteLine("{");

        foreach (var eventSymbol in events)
        {
            writer.WriteIndentation(1);
            writer.Write(eventSymbol.Name);
            writer.WriteLine(",");
        }

        writer.WriteLine("}");
    }

    private void WriteEvents(StringWriter writer, IEventSymbol[] events)
    {
        writer.WriteLine();

        writer.WriteLine("partial class GatewayEvent");
        writer.Write("{");

        foreach (var eventSymbol in events)
        {
            writer.WriteLine();

            writer.WriteInheritDoc(eventSymbol, 1);

            writer.WriteIndentation(1);
            writer.Write("public static global::");
            writer.Write(Namespace);
            writer.Write(".GatewayEvent");

            var eventType = (INamedTypeSymbol)eventSymbol.Type;
            if (eventType.Arity is 2)
            {
                writer.Write("<");
                writer.Write(eventType.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
                writer.Write(">");
            }

            writer.Write(" ");
            writer.Write(eventSymbol.Name);
            writer.Write(" => new(global::NetCord.Hosting.Gateway.GatewayEventId.");
            writer.Write(eventSymbol.Name);
            writer.WriteLine(");");
        }

        writer.WriteLine("}");
    }

    private string GenerateHandlerInterfaces(IEventSymbol[] events)
    {
        StringWriter writer = new();
        Setup(writer);

        WriteGatewayHandlerInterfaces(writer, events);

        return writer.ToString();
    }

    private void WriteGatewayHandlerInterfaces(StringWriter writer, IEventSymbol[] events)
    {
        foreach (var eventSymbol in events)
        {
            writer.WriteLine();

            writer.WriteInheritDoc(eventSymbol, 0);

            writer.Write("public interface I");
            writer.Write(eventSymbol.Name);
            writer.WriteLine("GatewayHandler : global::NetCord.Hosting.Gateway.IGatewayHandler");

            writer.WriteLine("{");

            var eventType = (INamedTypeSymbol)eventSymbol.Type;
            var hasArg = eventType.Arity is 2;

            WriteHandleAsyncXmlDoc(writer, false, hasArg);

            writer.WriteIndentation(1);
            writer.Write("public global::System.Threading.Tasks.ValueTask HandleAsync(");

            if (hasArg)
            {
                writer.Write(eventType.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
                writer.Write(" arg");
            }

            writer.WriteLine(");");

            writer.WriteLine("}");

            writer.WriteLine();

            writer.WriteInheritDoc(eventSymbol, 0);

            writer.Write("public interface I");
            writer.Write(eventSymbol.Name);
            writer.WriteLine("ShardedGatewayHandler : global::NetCord.Hosting.Gateway.IShardedGatewayHandler");

            writer.WriteLine("{");

            WriteHandleAsyncXmlDoc(writer, true, hasArg);

            writer.WriteIndentation(1);
            writer.Write("public global::System.Threading.Tasks.ValueTask HandleAsync(global::NetCord.Gateway.GatewayClient client");

            if (hasArg)
            {
                writer.Write(", ");
                writer.Write(eventType.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
                writer.Write(" arg");
            }

            writer.WriteLine(");");

            writer.WriteLine("}");
        }
    }

    private void WriteHandleAsyncXmlDoc(StringWriter writer, bool hasClient, bool hasArg)
    {
        writer.WriteIndentation(1);
        writer.WriteLine("/// <summary>");

        writer.WriteIndentation(1);
        writer.WriteLine("/// Handles the gateway event.");

        writer.WriteIndentation(1);
        writer.WriteLine("/// </summary>");

        if (hasClient)
        {
            writer.WriteIndentation(1);
            writer.WriteLine("/// <param name=\"client\">The gateway client that represents the shard that received the event.</param>");
        }

        if (hasArg)
        {
            writer.WriteIndentation(1);
            writer.WriteLine("/// <param name=\"arg\">The event argument.</param>");
        }
    }

    private string GenerateHandlerRegistrationMethods(IEventSymbol[] events)
    {
        StringWriter stringWriter = new();
        IndentedTextWriter writer = new(stringWriter);
        Setup(writer);

        WriteRegisterHandlerMethods(writer, events);

        return stringWriter.ToString();
    }

    private string GenerateShardedHandlerRegistrationMethods(IEventSymbol[] events)
    {
        StringWriter stringWriter = new();
        IndentedTextWriter writer = new(stringWriter);
        Setup(writer);

        WriteRegisterShardedHandlerMethods(writer, events);

        return stringWriter.ToString();
    }

    private void WriteRegisterHandlerMethods(IndentedTextWriter writer, IEventSymbol[] events)
    {
        writer.WriteLine();

        writer.WriteLine("partial class GatewayClientHostedService");

        writer.Write("{");

        WriteRegisterDelegateHandlerMethod(writer, events);

        WriteRegisterClassHandlerMethod(writer, events);

        writer.WriteLine("}");
    }

    private void WriteRegisterShardedHandlerMethods(IndentedTextWriter writer, IEventSymbol[] events)
    {
        writer.WriteLine();

        writer.WriteLine("partial class ShardedGatewayClientHostedService");

        writer.Write("{");

        WriteRegisterDelegateShardedHandlerMethod(writer, events);

        WriteRegisterClassShardedHandlerMethod(writer, events);

        writer.WriteLine("}");
    }

    private void WriteRegisterDelegateHandlerMethod(IndentedTextWriter writer, IEventSymbol[] events)
    {
        writer.WriteLine();

        writer.WriteLine("private static void RegisterDelegateHandler(IServiceProvider services, global::NetCord.Gateway.GatewayClient client, global::NetCord.Hosting.DelegateHandlerMetadata<global::NetCord.Hosting.Gateway.GatewayEventId> handlerMetadata)");

        writer.WriteLine("{");
        writer.Indent++;

        writer.WriteLine("var isSingleton = handlerMetadata.IsSingleton;");

        writer.WriteLine("switch (handlerMetadata.EventId)");

        writer.WriteLine("{");
        writer.Indent++;

        int eventsLength = events.Length;
        for (int i = 0; i < eventsLength; i++)
        {
            var eventSymbol = events[i];

            var eventType = (INamedTypeSymbol)eventSymbol.Type;

            writer.Write("case global::NetCord.Hosting.Gateway.GatewayEventId.");
            writer.Write(eventSymbol.Name);
            writer.WriteLine(":");
            writer.Indent++;

            writer.WriteLine("{");
            writer.Indent++;

            writer.Write("var rawHandler");
            writer.Write(" = (global::System.Func<");

            if (eventType.Arity is not 1)
            {
                writer.Write(eventType.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
                writer.Write(", ");
            }

            writer.WriteLine("global::System.IServiceProvider, global::System.Threading.Tasks.ValueTask>)handlerMetadata.Handler;");

            writer.Write(eventType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
            writer.WriteLine(" handler;");

            DelegateHandlerInvocationHelper.WriteDelegateHandlerInvocationDelegate(writer, eventType.Arity is 1 ? [] : ["arg"]);

            writer.Write("client.");
            writer.Write(eventSymbol.Name);
            writer.WriteLine(" += handler;");

            writer.WriteLine("break;");

            writer.Indent--;
            writer.WriteLine("}");
        }

        writer.Indent--;
        writer.WriteLine("}");

        writer.Indent--;
        writer.WriteLine("}");
    }

    private void WriteRegisterClassHandlerMethod(IndentedTextWriter writer, IEventSymbol[] events)
    {
        writer.WriteLine();

        writer.WriteLine("private static void RegisterClassHandler(global::System.IServiceProvider services, global::NetCord.Gateway.GatewayClient client, global::NetCord.Hosting.ClassHandlerMetadata handlerMetadata)");

        writer.WriteLine("{");
        writer.Indent++;

        int eventsLength = events.Length;

        for (int i = 0; i < eventsLength; i++)
        {
            var eventSymbol = events[i];

            var eventType = (INamedTypeSymbol)eventSymbol.Type;

            writer.WriteLine();

            writer.Write("if (typeof(global::NetCord.Hosting.Gateway.I");
            writer.Write(eventSymbol.Name);
            writer.WriteLine("GatewayHandler).IsAssignableFrom(handlerType))");

            writer.WriteLine("{");
            writer.Indent++;

            writer.Write(eventType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
            writer.WriteLine(" handler;");

            ClassHandlerInvocationHelper.WriteClassHandlerInvocationDelegate(writer, $"global::NetCord.Hosting.Gateway.I{eventSymbol.Name}GatewayHandler", eventType.Arity is 1 ? [] : ["arg"]);

            writer.Write("client.");
            writer.Write(eventSymbol.Name);
            writer.WriteLine(" += handler;");

            writer.Indent--;
            writer.WriteLine("}");
        }

        writer.Indent--;
        writer.WriteLine("}");
    }

    private void WriteRegisterDelegateShardedHandlerMethod(IndentedTextWriter writer, IEventSymbol[] events)
    {
        writer.WriteLine();

        writer.WriteLine("private static void RegisterDelegateShardedHandler(IServiceProvider services, global::NetCord.Gateway.ShardedGatewayClient client, global::NetCord.Hosting.DelegateHandlerMetadata<global::NetCord.Hosting.Gateway.GatewayEventId> handlerMetadata)");

        writer.WriteLine("{");
        writer.Indent++;

        writer.WriteLine("var isSingleton = handlerMetadata.IsSingleton;");

        writer.WriteLine("switch (handlerMetadata.EventId)");

        writer.WriteLine("{");
        writer.Indent++;

        int eventsLength = events.Length;
        for (int i = 0; i < eventsLength; i++)
        {
            var eventSymbol = events[i];

            var eventType = (INamedTypeSymbol)eventSymbol.Type;

            writer.Write("case global::NetCord.Hosting.Gateway.GatewayEventId.");
            writer.Write(eventSymbol.Name);
            writer.WriteLine(":");
            writer.Indent++;

            writer.WriteLine("{");
            writer.Indent++;

            writer.Write("var rawHandler");
            writer.Write(i);
            writer.Write(" = (global::System.Func<global::NetCord.Gateway.GatewayClient, ");
            if (eventType.Arity is not 1)
            {
                writer.Write(eventType.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
                writer.Write(", ");
            }

            writer.WriteLine("global::System.IServiceProvider, global::System.Threading.Tasks.ValueTask>)handlerMetadata.Handler;");

            DelegateHandlerInvocationHelper.WriteDelegateHandlerInvocationDelegate(writer, eventType.Arity is 1 ? ["client"] : ["client", "arg"]);

            writer.Write("client.");
            writer.Write(eventSymbol.Name);
            writer.WriteLine(" += handler;");

            writer.WriteLine("break;");

            writer.Indent--;
            writer.WriteLine("}");
        }

        writer.WriteIndentation(2);
        writer.WriteLine("}");

        writer.WriteIndentation(1);
        writer.WriteLine("}");
    }

    private void WriteRegisterClassShardedHandlerMethod(IndentedTextWriter writer, IEventSymbol[] events)
    {
        writer.WriteLine();

        writer.WriteLine("private static void RegisterClassShardedHandler(global::System.IServiceProvider services, global::NetCord.Gateway.ShardedGatewayClient client, global::NetCord.Hosting.ClassHandlerMetadata handlerMetadata)");

        writer.WriteLine("{");
        writer.Indent++;

        int eventsLength = events.Length;

        for (int i = 0; i < eventsLength; i++)
        {
            var eventSymbol = events[i];

            var eventType = (INamedTypeSymbol)eventSymbol.Type;

            writer.WriteLine();

            writer.Write("if (typeof(global::NetCord.Hosting.Gateway.I");
            writer.Write(eventSymbol.Name);
            writer.WriteLine("ShardedGatewayHandler).IsAssignableFrom(handlerType))");

            writer.WriteLine("{");
            writer.Indent++;

            writer.Write(eventType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
            writer.WriteLine(" handler;");

            ClassHandlerInvocationHelper.WriteClassHandlerInvocationDelegate(writer, $"global::NetCord.Hosting.Gateway.I{eventSymbol.Name}ShardedGatewayHandler", eventType.Arity is 2 ? ["client"] : ["client", "arg"]);

            writer.Write("client.");
            writer.Write(eventSymbol.Name);
            writer.WriteLine(" += handler;");

            writer.Indent--;
            writer.WriteLine("}");
        }

        writer.Indent--;
        writer.WriteLine("}");
    }

    private static IEventSymbol[] GetEvents(ImmutableArray<INamedTypeSymbol> typeSymbols)
    {
        return [.. typeSymbols.SelectMany(symbol => symbol.GetMembers()).OfType<IEventSymbol>()];
    }
}
