name: Build NetCord.Natives

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      GenerateBinLog:
        type: boolean
        default: false
  push:
    paths:
      - 'NetCord.Natives/**'
      - 'Tests/NetCord.Natives.Tests/**'
      - '.github/workflows/build-natives.yml'

jobs:
  build-natives:
    runs-on: ${{ matrix.runs-on }}
    env:
      CI: true
      VCPKG_BINARY_SOURCES: clear;files,${{ github.workspace }}/.vcpkg-cache,readwrite
      VCPKG_DOWNLOADS: ${{ github.workspace }}/.vcpkg-downloads
      VcpkgOSTarget: ${{ matrix.vcpkg-os-target }}
      VcpkgPlatformTarget: ${{ matrix.vcpkg-platform-target }}
      Configuration: Release
      RuntimeIdentifier: ${{ matrix.rid }}
      DotnetVerbose: minimal
      GenerateBinLog: ${{ github.event.inputs.GenerateBinLog || inputs.GenerateBinLog || false }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - rid: win-x64
            runs-on: windows-latest
            vcpkg-os-target: windows
            vcpkg-platform-target: x64
          - rid: win-arm64
            runs-on: windows-11-arm
            vcpkg-os-target: windows
            vcpkg-platform-target: arm64
          - rid: osx-x64
            runs-on: macos-15-intel
            vcpkg-os-target: osx
            vcpkg-platform-target: x64
          - rid: osx-arm64
            runs-on: macos-15
            vcpkg-os-target: osx
            vcpkg-platform-target: arm64
          - rid: linux-x64
            runs-on: ubuntu-latest
            vcpkg-os-target: linux
            vcpkg-platform-target: x64
          - rid: linux-arm64
            runs-on: ubuntu-24.04-arm
            vcpkg-os-target: linux
            vcpkg-platform-target: arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Restore vcpkg cache
        uses: actions/cache/restore@v5.0.5
        with:
          path: |
            .vcpkg-cache
            .vcpkg-downloads
          key: vcpkg-${{ runner.os }}-${{ matrix.rid }}-${{ hashFiles('NetCord.Natives/vcpkg.json', 'NetCord.Natives/natives-ports/**') }}
          restore-keys: |
            vcpkg-${{ runner.os }}-${{ matrix.rid }}-
            vcpkg-${{ runner.os }}-

      - name: Setup vcpkg
        uses: ./.github/actions/setup-vcpkg

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v5.2.0
        with:
          global-json-file: global.json

      - name: Install native build tools (macOS)
        if: runner.os == 'macOS'
        shell: bash
        run: |
          brew update
          for pkg in autoconf automake libtool; do
            brew list $pkg &>/dev/null || brew install $pkg
          done

      - name: Restore
        shell: pwsh
        run: |
          dotnet restore Tests/NetCord.Natives.Tests/NetCord.Natives.Tests.csproj -v ${{ env.DotnetVerbose }} ${{ env.GenerateBinLog == 'true' && '-bl:restore.binlog' || '' }}

      - name: Build natives projects for ${{ matrix.rid }}
        shell: pwsh
        run: > # Building tests will build dependencies including the native libraries
          dotnet build Tests/NetCord.Natives.Tests/NetCord.Natives.Tests.csproj --no-restore -v ${{ env.DotnetVerbose }} 
          ${{ env.GenerateBinLog == 'true' && '-bl:build.binlog' || '' }}
          -p:AppendNativeAotAppProps="RuntimeIdentifier=${{ env.RuntimeIdentifier }}" 
          -p:GeneratePackageOnBuild=false -p:CI=false

      - name: Test natives outputs for ${{ matrix.rid }}
        shell: pwsh
        run: >
          dotnet test Tests/NetCord.Natives.Tests/NetCord.Natives.Tests.csproj --no-restore --no-build -v ${{ env.DotnetVerbose }} 
          ${{ env.GenerateBinLog == 'true' && '-bl:test.binlog' || '' }}
          --logger "console;verbosity=detailed" 
          --logger GitHubActions 

      - name: Pack NuGet Package for ${{ matrix.rid }}
        if: ${{ always() }}
        shell: pwsh
        run: >
          dotnet pack NetCord.Natives/NetCord.Natives.csproj --no-restore --no-build -v ${{ env.DotnetVerbose }} 
          ${{ env.GenerateBinLog == 'true' && '-bl:pack.binlog' || '' }}
          -o NetCord.Natives/bin/${{ matrix.rid }} 
          -p:CI=false

      - name: Upload Binary Logs
        if: ${{ env.GenerateBinLog == 'true' && always() }}
        uses: actions/upload-artifact@v4.6.0
        with:
          name: ${{ matrix.rid }}-binlogs
          path: |
            *.binlog

      - name: Upload NuGet Package Artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v7.0.1
        with:
          name: NetCord.Natives.${{ matrix.rid }}.packages
          path: |
            NetCord.Natives/bin/${{ matrix.rid }}/*.nupkg
            NetCord.Natives/bin/${{ matrix.rid }}/*.snupkg

      - name: Save vcpkg cache
        if: ${{ always() }}
        uses: actions/cache/save@v5.0.5
        with:
          path: |
            .vcpkg-cache
            .vcpkg-downloads
          key: vcpkg-${{ runner.os }}-${{ matrix.rid }}-${{ hashFiles('NetCord.Natives/vcpkg.json', 'NetCord.Natives/natives-ports/**') }}
