name: Build and Publish

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+-*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Install Nix
        uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6

      - name: Setup dev environment
        shell: &dev-shell 'nix develop -c bash -eo pipefail {0}'
        run: 'true'

      - name: Restore dependencies
        shell: *dev-shell
        run: dotnet restore

      - name: Build
        shell: *dev-shell
        run: dotnet build -c Release --no-restore --warnaserror

      - name: Test
        shell: *dev-shell
        run: dotnet test -c Release --no-build --verbosity normal

      - name: Pack Packages
        shell: *dev-shell
        run: |
          dotnet pack NetCord -c Release --no-build
          dotnet pack NetCord.Services -c Release --no-build
          dotnet pack Hosting/NetCord.Hosting -c Release --no-build
          dotnet pack Hosting/NetCord.Hosting.Services -c Release --no-build
          dotnet pack Hosting/NetCord.Hosting.AspNetCore -c Release --no-build

      - name: Setup docs environment
        shell: &docs-shell 'nix develop .#docs -c bash -eo pipefail {0}'
        run: 'true'

      - name: Build Documentation
        shell: *docs-shell
        working-directory: Documentation
        run: |
          npm install
          npm run lint
          npm run test
          npm run build

      - name: Publish Packages
        shell: *dev-shell
        env:
          KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          dotnet nuget push NetCord/bin/Release/*.nupkg -k $KEY -s https://api.nuget.org/v3/index.json --skip-duplicate
          dotnet nuget push NetCord.Services/bin/Release/*.nupkg -k $KEY -s https://api.nuget.org/v3/index.json --skip-duplicate
          dotnet nuget push Hosting/NetCord.Hosting/bin/Release/*.nupkg -k $KEY -s https://api.nuget.org/v3/index.json --skip-duplicate
          dotnet nuget push Hosting/NetCord.Hosting.Services/bin/Release/*.nupkg -k $KEY -s https://api.nuget.org/v3/index.json --skip-duplicate
          dotnet nuget push Hosting/NetCord.Hosting.AspNetCore/bin/Release/*.nupkg -k $KEY -s https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Deploy Documentation
        uses: appleboy/scp-action@ff85246acaad7bdce478db94a363cd2bf7c90345 # v1.0.0
        with:
          username: ${{ secrets.SSH_USERNAME }}
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          rm: true
          source: Documentation/_site
          strip_components: 2
          target: ~/NetCord/html

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
          TAG: ${{ github.ref_name }}
          IS_PRERELEASE: ${{ contains(github.ref_name, '-') }}
        run: |
          cp -r Documentation/_site "Documentation-$TAG"

          zip -r "Documentation-$TAG.zip" "Documentation-$TAG"
          tar -czvf "Documentation-$TAG.tar.gz" "Documentation-$TAG"

          rm -r "Documentation-$TAG"

          FILES=(
            NetCord/bin/Release/*.*nupkg
            NetCord.Services/bin/Release/*.*nupkg
            Hosting/NetCord.Hosting/bin/Release/*.*nupkg
            Hosting/NetCord.Hosting.Services/bin/Release/*.*nupkg
            Hosting/NetCord.Hosting.AspNetCore/bin/Release/*.*nupkg
            "Documentation-$TAG.zip"
            "Documentation-$TAG.tar.gz"
          )

          if gh release view "$TAG" >/dev/null 2>&1; then
            gh release upload "$TAG" \
              --clobber \
              "${FILES[@]}"
          else
            gh release create "$TAG" \
              --generate-notes \
              --prerelease="$IS_PRERELEASE" \
              "${FILES[@]}"
          fi

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Build Artifacts
          path: |
            NetCord/bin/Release
            NetCord.Services/bin/Release
            Hosting/NetCord.Hosting/bin/Release
            Hosting/NetCord.Hosting.Services/bin/Release
            Hosting/NetCord.Hosting.AspNetCore/bin/Release

      - name: Upload Documentation Artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Documentation Artifacts
          path: Documentation/_site
