name: Build and Publish

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+-*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          filter: tree:0

      - uses: cachix/install-nix-action@v31

      - name: Setup dev environment
        shell: &dev-shell 'nix develop -c bash -e {0}'
        run: 'true'

      - name: Restore dependencies
        shell: *dev-shell
        run: dotnet restore

      - name: Build
        shell: *dev-shell
        run: dotnet build -c Release --no-restore --warnaserror

      - name: Test
        shell: *dev-shell
        run: dotnet test -c Release --no-build --verbosity normal

      - name: Pack Packages
        shell: *dev-shell
        run: |
          dotnet pack NetCord -c Release --no-build
          dotnet pack NetCord.Services -c Release --no-build
          dotnet pack Hosting/NetCord.Hosting -c Release --no-build
          dotnet pack Hosting/NetCord.Hosting.Services  -c Release --no-build
          dotnet pack Hosting/NetCord.Hosting.AspNetCore -c Release --no-build

      - name: Setup docs environment
        shell: &docs-shell 'nix develop .#docs -c bash -e {0}'
        run: 'true'

      - name: Build Documentation
        shell: *docs-shell
        working-directory: Documentation
        run: |
          npm install
          npm run lint
          npm run test
          npm run build

      - name: Publish Packages
        env:
          KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          dotnet nuget push NetCord/bin/Release/*.nupkg -k $KEY -s https://api.nuget.org/v3/index.json --skip-duplicate
          dotnet nuget push NetCord.Services/bin/Release/*.nupkg -k $KEY -s https://api.nuget.org/v3/index.json --skip-duplicate
          dotnet nuget push Hosting/NetCord.Hosting/bin/Release/*.nupkg -k $KEY -s https://api.nuget.org/v3/index.json --skip-duplicate
          dotnet nuget push Hosting/NetCord.Hosting.Services/bin/Release/*.nupkg -k $KEY -s https://api.nuget.org/v3/index.json --skip-duplicate
          dotnet nuget push Hosting/NetCord.Hosting.AspNetCore/bin/Release/*.nupkg -k $KEY -s https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Deploy Documentation
        uses: appleboy/scp-action@ff85246acaad7bdce478db94a363cd2bf7c90345 # v1.0.0
        with:
          username: ${{ secrets.SSH_USERNAME }}
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          rm: true
          source: Documentation/_site
          strip_components: 2
          target: ~/NetCord/html

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: Build Artifacts
          path: |
            NetCord/bin/Release
            NetCord.Services/bin/Release
            Hosting/NetCord.Hosting/bin/Release
            Hosting/NetCord.Hosting.Services/bin/Release
            Hosting/NetCord.Hosting.AspNetCore/bin/Release

      - name: Upload Documentation Artifacts
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: Documentation Artifacts
          path: Documentation/_site
